### ISSUE TITLE
 直接依赖的两个jar 包，上传文件 选择拍照崩溃， 选择相册图片没有问题，请问大佬知道原因么

### ISSUE THREAD

**Issue by BayMaxM** [Justson/AgentWeb#1010]
java.lang.IllegalStateException: showFileChooser result was already called
        at UE0.onReceiveValue(chromium-TrichromeWebViewGoogle6432.aab-stable-506012934:890)
        at com.just.agentweb.filechooser.FileChooser.cancel(FileChooser.java:480)
        at com.just.agentweb.filechooser.FileChooser.onIntentResult(FileChooser.java:422)
        at com.just.agentweb.filechooser.FileChooser$2.onChoiceResult(FileChooser.java:244)
        at com.just.agentweb.AgentActionFragment.captureCamera(AgentActionFragment.java:195)
        at com.just.agentweb.AgentActionFragment.runAction(AgentActionFragment.java:104)
        at com.just.agentweb.AgentActionFragment.onCreate(AgentActionFragment.java:84)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8291)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by Justson** [comment]
```
 implementation 'com.github.Justson.AgentWeb:agentweb-core:v5.0.6-androidx' // (必选)
 implementation 'com.github.Justson.AgentWeb:agentweb-filechooser:v5.0.6-androidx' // (可选)
 implementation 'com.github.Justson:Downloader:v5.0.4-androidx'
```
