### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by liecen** [Justson/AgentWeb#1032]
android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:332)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2594)
        at android.content.res.Resources.getLayout(Resources.java:1400)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:550)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:814)
        at android.app.Dialog.show(Dialog.java:454)
        at com.just.agentweb.DefaultUIController.onShowSslCertificateErrorDialog(DefaultUIController.java:405)
        at com.just.agentweb.AgentWebUIControllerImplBase.onShowSslCertificateErrorDialog(AgentWebUIControllerImplBase.java:103)
        at com.just.agentweb.DefaultWebClient.onReceivedSslError(DefaultWebClient.java:469)
        at IG.onReceivedSslError(HwWebview-12.0.0.325.4096:3)
        at c5.onReceivedSslError(HwWebview-12.0.0.325.4096:1)
        at o5.run(HwWebview-12.0.0.325.4096:1)
        at android.os.Handler.handleCallback(Handler.java:955)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:206)
        at android.os.Looper.loop(Looper.java:296)
        at android.app.ActivityThread.main(ActivityThread.java:8971)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)

**Comment by liecen** [comment]
<style name="MyDialogTheme" parent="Theme.AppCompat.Light.Dialog.Alert" />

AlertDialog.Builder builder = new AlertDialog.Builder(getActivity(),R.style.MyDialogTheme);
