### ISSUE TITLE
市场隐私合格审核报获取特殊传感器问题 日志如下

### ISSUE THREAD

**Issue by gitxiaojin** [Justson/AgentWeb#1060]
at android.hardware.SensorManager.getSensorList() at org.chromium.device.sensors.PlatformSensor.a(chromium-SystemWebViewGoogle.aab-stable-1:2) at org.chromium.device.sensors.PlatformSensorProvider.createSensor(chromium-SystemWebViewGoogle.aab-stable-1:5) at android.os.MessageQueue.nativePollOnce(Native Method) at android.os.MessageQueue.next(MessageQueue.java:325) at android.os.Looper.loop(Looper.java:142) at android.app.ActivityThread.main(ActivityThread.java:6554) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

我和小米市场的审核人员沟通他们反馈：
可能是APP内部网页中包含部分组件（如js代码等）调用了传感器信息
请参考日志中的堆栈 可能是APP调用webview显示网页 网页中的组件通过APP调用了传感器信息
我们的网页就是一个静态的页面

**Comment by ByteRax** [comment]
和AgentWeb其实无关，只要你new Webview ，webview 内部就会获取传感器。解决办法就是hook SensorManager

**Comment by songjunhaoQAQ** [comment]
你好，请问解决了吗

**Comment by FrizzleLiu** [comment]
我这边查到的是H5页面视频播放器播放时候调用了这个api

**Comment by Justson** [comment]
这部分调用来自系统 WebView，不是 AgentWeb 发起的。

堆栈已经说明了来源：

```
org.chromium.device.sensors.PlatformSensorProvider.createSensor
org.chromium.device.sensors.PlatformSensor.a
  └─ SensorManager.getSensorList()
```

`org.chromium.device.sensors` 是 Chromium 实现 W3C 传感器 API（`DeviceOrientationEvent` / `DeviceMotionEvent` 等）的模块。WebView 初始化时会探测设备具备哪些传感器能力，即便页面是静态的也会触发——这是系统 WebView 组件的固有行为，换成原生 `WebView` 同样如此。

**答复审核时可以这样说明**：该调用由系统 WebView 组件（`com.google.android.webview` / `com.android.webview`）在初始化时发起，用于向网页提供标准的 W3C 传感器 API，应用自身代码未调用 `SensorManager`。可以让审核人员注意堆栈中的 `chromium-SystemWebViewGoogle` 标识。

AgentWeb 这边没有可关闭的开关（`WebSettings` 未提供禁用传感器 API 的接口）。与 #1079 是同一件事的两面，一并说明。
