### ISSUE TITLE
您好！调用摄像头遇到了崩溃问题，请问这个应该怎么解决？

### ISSUE THREAD

**Issue by lt-lxy1215** [Justson/AgentWeb#1071]
FATAL EXCEPTION: VideoCaptureCamera2_CameraThread
Process: com.just.agentweb.sample, PID: 16046
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Rect.width()' on a null object reference
         at Nd.run(PG:74)
         at android.os.Handler.handleCallback(Handler.java:808)
         at android.os.Handler.dispatchMessage(Handler.java:101)
         at android.os.Looper.loop(Looper.java:166)
         at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)
