### ISSUE TITLE
下载的时候报错

### ISSUE THREAD

**Issue by kjsolo** [Justson/AgentWeb#171]
用的support版本是27.0.2
```
java.lang.IllegalAccessError: Field 'android.support.v4.app.NotificationCompat$Builder.mNotification' is inaccessible to class 'com.just.library.Notify' (declaration of 'com.just.library.Notify' appears in /data/app/cn.soloho.oraclebb-1/base.apk:classes8.dex)
at com.just.library.Notify.hasDeleteContent(Notify.java:120)
at com.just.library.RealDownLoader.onProgressUpdate(RealDownLoader.java:175)
at com.just.library.RealDownLoader.onProgressUpdate(RealDownLoader.java:31)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:680)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by Justson** [comment]
感谢你的反馈 ，  下个版本修复 。

**Comment by mstbetter** [comment]
我也遇到这样的问题，怎么解决的

**Comment by Justson** [comment]
@mstbetter 使用最新版

**Comment by mstbetter** [comment]
> @mstbetter 使用最新版

下载用了还是报错     
 implementation 'com.github.Justson.AgentWeb:agentweb-core:v4.1.9' // (必选)
 implementation 'com.github.Justson.AgentWeb:agentweb-filechooser:v4.1.9' // (可选)
 implementation 'com.github.Justson:Downloader:v4.1.9' // (可选)

**Comment by mstbetter** [comment]
第一次crash  ，第二次点就ok

**Comment by Justson** [comment]
@mstbetter  贴下日志吗?

**Comment by mstbetter** [comment]
java.lang.IllegalAccessError: Field 'android.support.v4.app.NotificationCompat$Builder.mNotification' is inaccessible to class 'com.just.library.Notify' (declaration of 'com.just.library.Notify' appears in /data/app/cn.soloho.oraclebb-1/base.apk:classes8.dex)
at com.just.library.Notify.hasDeleteContent(Notify.java:120)
at com.just.library.RealDownLoader.onProgressUpdate(RealDownLoader.java:175)
at com.just.library.RealDownLoader.onProgressUpdate(RealDownLoader.java:31)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:680)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
