### ISSUE TITLE
父布局被scrollview包裹报错

### ISSUE THREAD

**Issue by tanzhixue** [Justson/AgentWeb#189]
java.lang.IllegalStateException: Unable to create layer for WebView, size 1080x9552 exceeds max size 8192
                                                               at android.os.MessageQueue.nativePollOnce(Native Method)
                                                               at android.os.MessageQueue.next(MessageQueue.java:356)
                                                               at android.os.Looper.loop(Looper.java:138)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by tanzhixue** [comment]
已解决
第一步关闭硬件加速android:hardwareAccelerated="true"
第二步 WebView mWebView=mAgentWeb.getWebCreator().get();
		mWebView.setLayerType(View.LAYER_TYPE_NONE, null);
希望能帮到别人
