### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Vaitt-Joy** [Justson/AgentWeb#199]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/WebResourceError;
	at com.just.agentweb.v.a(SourceFile:446)
	at com.just.agentweb.v.onReceivedError(SourceFile:422)
	at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedError(WebViewContentsClientAdapter.java:244)
	at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5911)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.WebResourceError" on path: DexPathList[[zip file "/data/app/com.bxvip.app.haocai_test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx.test-1/lib/arm64, /vendor/lib64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 11 more
	Suppressed: java.lang.ClassNotFoundException: android.webkit.WebResourceError
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 12 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by Vaitt-Joy** [comment]
http://blog.csdn.net/barryhappy/article/details/52733406 好像是兼容问题
