### ISSUE TITLE
访问一些需要定位权限的网址时,会出现找不到某个资源的id而崩溃

### ISSUE THREAD

**Issue by ppg408331701** [Justson/AgentWeb#202]
例如访问百度的时候,会弹出提示请求定位权限,然后点击允许之后就会崩溃
第二次打开就问题了

` E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.webapps.yier, PID: 13446
                                                                  android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                      at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
                                                                      at android.content.res.Resources.loadXmlResourceParser(Resources.java:2105)
                                                                      at android.content.res.Resources.getLayout(Resources.java:1119)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                                                                      at com.just.agentweb.WebParentLayout.createErrorLayout(WebParentLayout.java:68)
                                                                      at com.just.agentweb.WebParentLayout.showPageMainFrameError(WebParentLayout.java:58)
                                                                      at com.just.agentweb.DefaultUIController.onMainFrameError(DefaultUIController.java:230)
                                                                      at com.just.agentweb.AgentWebUIControllerImplBase.onMainFrameError(AgentWebUIControllerImplBase.java:52)
                                                                      at com.just.agentweb.DefaultWebClient.onMainFrameError(DefaultWebClient.java:435)
                                                                      at com.just.agentweb.DefaultWebClient.onReceivedError(DefaultWebClient.java:410)
                                                                      at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedError2(WebViewContentsClientAdapter.java:627)
                                                                      at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:7357)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:241)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

**Comment by Justson** [comment]
该问题已经修复了，你可以升级到rc版。谢谢你的反馈

**Comment by duyangs** [comment]
无网络情况也会出现这个问题 找不到资源
`Process: com.brightcns.liangla.xiamen, PID: 3748
                                                 android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
                                                     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2101)
                                                     at android.content.res.Resources.getLayout(Resources.java:1115)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                                                     at com.just.agentweb.WebParentLayout.createErrorLayout(WebParentLayout.java:68)
                                                     at com.just.agentweb.WebParentLayout.showPageMainFrameError(WebParentLayout.java:58)
                                                     at com.just.agentweb.DefaultUIController.onMainFrameError(DefaultUIController.java:230)
                                                     at com.just.agentweb.AgentWebUIControllerImplBase.onMainFrameError(AgentWebUIControllerImplBase.java:52)
                                                     at com.just.agentweb.DefaultWebClient.onMainFrameError(DefaultWebClient.java:435)
                                                     at com.just.agentweb.DefaultWebClient.onReceivedError(DefaultWebClient.java:410)
                                                     at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedError2(WebViewContentsClientAdapter.java:627)
                                                     at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:7357)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6196)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`
