### ISSUE TITLE
无网络情况 加载webview 运行时异常 找不到资源

### ISSUE THREAD

**Issue by duyangs** [Justson/AgentWeb#233]
`01-22 11:44:02.174 3748-3748/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.brightcns.liangla.xiamen, PID: 3748
                                                 android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
                                                     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2101)
                                                     at android.content.res.Resources.getLayout(Resources.java:1115)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                                                     at com.just.agentweb.WebParentLayout.createErrorLayout(WebParentLayout.java:68)
                                                     at com.just.agentweb.WebParentLayout.showPageMainFrameError(WebParentLayout.java:58)
                                                     at com.just.agentweb.DefaultUIController.onMainFrameError(DefaultUIController.java:230)
                                                     at com.just.agentweb.AgentWebUIControllerImplBase.onMainFrameError(AgentWebUIControllerImplBase.java:52)
                                                     at com.just.agentweb.DefaultWebClient.onMainFrameError(DefaultWebClient.java:435)
                                                     at com.just.agentweb.DefaultWebClient.onReceivedError(DefaultWebClient.java:410)
                                                     at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedError2(WebViewContentsClientAdapter.java:627)
                                                     at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:7357)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6196)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

**Comment by Justson** [comment]
AgentWeb  最新版本吗?

**Comment by duyangs** [comment]
我的锅 更新到最新版 OK 了
