### ISSUE TITLE
oppo报错：java.lang.NoSuchMethodError: No virtual method requestPermissions

### ISSUE THREAD

**Issue by parcool** [Justson/AgentWeb#237]
FATAL EXCEPTION: main
                                                                                              Process: com.yibogame.vipwebviewplayer.vipwebviewplayer, PID: 6876
                                                                                              java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Lcom/just/library/ActionActivity; or its super classes (declaration of 'com.just.library.ActionActivity' appears in /data/app/com.yibogame.vipwebviewplayer.vipwebviewplayer-2/split_lib_dependencies_apk.apk)
                                                                                                  at com.just.library.ActionActivity.permission(ActionActivity.java:134)
                                                                                                  at com.just.library.ActionActivity.onCreate(ActionActivity.java:59)
                                                                                                  at android.app.Activity.performCreate(Activity.java:6107)
                                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2568)
                                                                                                  at android.app.ActivityThread.access$1000(ActivityThread.java:164)
                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1453)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                  at android.os.Looper.loop(Looper.java:159)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5532)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by Simonhy** [comment]
报同样的错误  怎么解决的

**Comment by parcool** [comment]
Sorry，我忘了。。。

**Comment by ju5t4fun** [comment]
系统版本Android5.1，在AgentWeb 2.0.1 上出现了同样的问题，最后发现是ActionActivity.java里调用requestPermissions没有判断系统版本，requestPermissions是在Android 6.0才加上的，在Android 5.1上调用就会出现异常，暂时没有试验最新版本的AgentWeb是否还有这个问题
