### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by Richard-person** [Justson/AgentWeb#260]
android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:226)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2166)
	at android.content.res.Resources.getLayout(Resources.java:1162)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at com.just.agentweb.WebParentLayout.e(WebParentLayout.java:68)
	at com.just.agentweb.WebParentLayout.a(WebParentLayout.java:58)
	at com.just.agentweb.r.a(DefaultUIController.java:230)
	at com.just.agentweb.h.a(AgentWebUIControllerImplBase.java:52)
	at com.just.agentweb.DefaultWebClient.a(DefaultWebClient.java:435)
	at com.just.agentweb.DefaultWebClient.onReceivedError(DefaultWebClient.java:410)
	at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedError2(WebViewContentsClientAdapter.java:626)
	at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:7357)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:181)
	at android.app.ActivityThread.main(ActivityThread.java:6273)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)

**Comment by Justson** [comment]
AgentWeb 版本？

**Comment by Richard-person** [comment]
目前是 compile 'com.just.agentweb:agentweb:3.0.0-beta' 版本，以前的版本也有这个问题,在某些机型会偶尔出现。

**Comment by Richard-person** [comment]
机型：HUAWEI-TIT-CL10    系统 ：Android 5.1
机型：红米note4x    系统：Android 7.0

**Comment by Justson** [comment]
升级下库？
