### ISSUE TITLE
7.0适配问题

### ISSUE THREAD

**Issue by badjone** [Justson/AgentWeb#332]
E/ConnectivityManager: java.lang.Throwable
                                                                         at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:2931)
                                                                         at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:3177)
                                                                         at org.chromium.android_webview.AwNetworkChangeNotifierRegistrationPolicy.onFirstWebViewCreated(AwNetworkChangeNotifierRegistrationPolicy.java:31)
                                                                         at org.chromium.android_webview.AwContentsLifecycleNotifier.onWebViewCreated(AwContentsLifecycleNotifier.java:7)
                                                                         at org.chromium.android_webview.AwContents.nativeInit(Native Method)
                                                                         at org.chromium.android_webview.AwContents.<init>(AwContents.java:80)
                                                                         at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:12)
                                                                         at com.android.webview.chromium.WebViewChromiumFactoryProvider$WebViewChromiumRunQueue.drainQueue(WebViewChromiumFactoryProvider.java:14)
                                                                         at com.android.webview.chromium.WebViewChromiumFactoryProvider$WebViewChromiumRunQueue$1.run(WebViewChromiumFactoryProvider.java:2)
                                                                         at org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:30)
                                                                         at com.android.webview.chromium.WebViewChromiumFactoryProvider$WebViewChromiumRunQueue.addTask(WebViewChromiumFactoryProvider.java:8)
                                                                         at com.android.webview.chromium.WebViewChromiumFactoryProvider.addTask(WebViewChromiumFactoryProvider.java:16)
                                                                         at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:65)
                                                                         at android.webkit.WebView.<init>(WebView.java:636)
                                                                         at android.webkit.WebView.<init>(WebView.java:572)
                                                                         at android.webkit.WebView.<init>(WebView.java:555)
                                                                         at android.webkit.WebView.<init>(WebView.java:542)
                                                                         at android.webkit.WebView.<init>(WebView.java:532)
                                                                         at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:240)
                                                                         at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:181)
                                                                         at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:157)
                                                                         at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34)
                                                                         at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:197)
                                                                         at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43)
                                                                         at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:567)
                                                                         at com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:499)
                                                                         at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:706)

**Comment by badjone** [comment]
Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$7>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;
     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
     at android.webkit.WebView com.just.agentweb.DefaultWebCreator.createWebView() (DefaultWebCreator.java:240)
     at android.view.ViewGroup com.just.agentweb.DefaultWebCreator.createLayout() (DefaultWebCreator.java:181)
     at com.just.agentweb.DefaultWebCreator com.just.agentweb.DefaultWebCreator.create() (DefaultWebCreator.java:157)
     at com.just.agentweb.WebCreator com.just.agentweb.DefaultWebCreator.create() (DefaultWebCreator.java:34)
     at void com.just.agentweb.AgentWeb.<init>(com.just.agentweb.AgentWeb$AgentBuilder) (AgentWeb.java:197)
     at void com.just.agentweb.AgentWeb.<init>(com.just.agentweb.AgentWeb$AgentBuilder, com.just.agentweb.AgentWeb$1) (AgentWeb.java:43)
     at com.just.agentweb.AgentWeb$PreAgentWeb com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb() (AgentWeb.java:567)
     at com.just.agentweb.AgentWeb$PreAgentWeb com.just.agentweb.AgentWeb$AgentBuilder.access$3700(com.just.agentweb.AgentWeb$AgentBuilder) (AgentWeb.java:499)
     at com.just.agentweb.AgentWeb$PreAgentWeb com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb() (AgentWeb.java:706)

**Comment by wonxll** [comment]
我也遇到这个问题

**Comment by zczhzy** [comment]
我也遇到了，华为手机，7.0系统

**Comment by fengyupianzhou** [comment]
<application android:usesCleartextTraffic="true">

**Comment by niyaode** [comment]
我也遇到，华为 9系统
```
Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
Accessing hidden method Landroid/text/SpannableStringInternal;->length()I (light greylist, linking)
Starting profile saver IsSaveProfileNow end.
Rejecting re-init on previously-failed class java.lang.Class<com.just.agentweb.DefaultDownloadImpl$4>: java.lang.NoClassDefFoundError: Failed resolution of:  @Lcom/download/library/DownloadListenerAdapter;
```
@Justson

**Comment by ChengMoumou** [comment]
有解决的嘛
