### ISSUE TITLE
Vivo手机加载demo，网页全部加载不出来，请大佬瞅一眼

### ISSUE THREAD

**Issue by wangchang163** [Justson/AgentWeb#390]
07-18 11:17:51.711 12113-12113/com.just.agentweb.sample I/ agentweb - DefaultDesignUIController: mWebParentLayout onMainFrameError:com.just.agentweb.WebParentLayout{fcc71cc V.E...... ........ 0,96-720,1232 #7f0e0021 app:id/web_parent_layout_id}
07-18 11:17:51.711 12113-12113/com.just.agentweb.sample I/ agentweb - DefaultWebClient: onReceivedError:com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl@f965e8
07-18 11:17:51.711 12113-12113/com.just.agentweb.sample W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12113
07-18 11:17:51.731 12113-12113/com.just.agentweb.sample W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12113
07-18 11:17:51.731 12113-12113/com.just.agentweb.sample D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: true
07-18 11:17:51.731 12113-12113/com.just.agentweb.sample D/cr_Ime: [InputMethodManagerWrapper.java:68] hideSoftInputFromWindow
07-18 11:17:51.741 12113-12113/com.just.agentweb.sample I/ agentweb - WebIndicator: mCurrentProgress:0.625 v:100.0  :0.375
07-18 11:17:55.601 12113-12113/com.just.agentweb.sample I/ agentweb - WebIndicator: mCurrentProgress:1.0E-8 v:95.0  :1.0
07-18 11:17:55.611 12113-12113/com.just.agentweb.sample I/Info: BaseWebActivity onPageStarted
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample I/ agentweb - AgentWebUtils:   methodName:onReceivedError   method:android.webkit.WebViewClient.onReceivedError
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample I/ agentweb - AgentWebUtils: isOverriedMethod:false
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err: java.lang.NoSuchMethodException: onMainFrameError [class com.just.agentweb.AbsAgentWebUIController, class android.webkit.WebView, int, class java.lang.String, class java.lang.String]
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at java.lang.Class.getMethod(Class.java:624)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:586)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at com.just.agentweb.AgentWebUtils.isExistMethod(AgentWebUtils.java:415)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at com.just.agentweb.DefaultWebClient.onMainFrameError(DefaultWebClient.java:511)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at com.just.agentweb.DefaultWebClient.onReceivedError(DefaultWebClient.java:499)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.onReceivedError2(WebViewContentsClientAdapter.java:604)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at org.chromium.android_webview.AwContentsClient.onReceivedError(AwContentsClient.java:357)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:160)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5563)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample I/ agentweb - DefaultDesignUIController: mWebParentLayout onMainFrameError:com.just.agentweb.WebParentLayout{fcc71cc V.E...... ........ 0,96-720,1232 #7f0e0021 app:id/web_parent_layout_id}
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample I/ agentweb - DefaultWebClient: onReceivedError:com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl@ca91f3d
07-18 11:17:55.621 12113-12113/com.just.agentweb.sample W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12113
07-18 11:17:55.641 12113-12113/com.just.agentweb.sample W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12113

**Comment by wangchang163** [comment]
问题： java.lang.NoSuchMethodException: onMainFrameError [class com.just.agentweb.AbsAgentWebUIController, class android.webkit.WebView, int, class java.lang.String, class java.lang.String]
问题2：07-18 11:17:55.641 12113-12113/com.just.agentweb.sample W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 12113
