### ISSUE TITLE
在使用AgentWeb 中下载遇到两个报错的bug

### ISSUE THREAD

**Issue by CQBOBOZHU** [Justson/AgentWeb#429]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.just.agentweb.download.DefaultDownloadImpl$ExtraServiceImpl.getHeaders()' on a null object reference
	at com.just.agentweb.download.f.a(Downloader.java:327)
	at com.just.agentweb.download.f.d(Downloader.java:228)
	at com.just.agentweb.download.f.a(Downloader.java:205)
	at com.just.agentweb.download.f.doInBackground(Downloader.java:56)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.just.agentweb.download.DefaultDownloadImpl$ExtraServiceImpl.getHeaders()' on a null object reference
	at com.just.agentweb.download.f.a(Downloader.java:327)
	at com.just.agentweb.download.f.d(Downloader.java:228)
	at com.just.agentweb.download.f.a(Downloader.java:205)
	at com.just.agentweb.download.f.doInBackground(Downloader.java:56)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
  这个是通过友盟统计采集到了，具体什么原因引起的也不知道。
机型  vivo Y67L   android 6.0  
另外 还有一个 报错

java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/7FF2-7FEB/Android/data/com.sj.woekapp/cache/agentweb-cache/com.zhuyu.bi.loans_1.0.25_25.apk
	at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
	at com.just.agentweb.h.b(AgentWebUtils.java:243)
	at com.just.agentweb.h.a(AgentWebUtils.java:235)
	at com.just.agentweb.h.a(AgentWebUtils.java:254)
	at com.just.agentweb.h.c(AgentWebUtils.java:696)
	at com.just.agentweb.download.DefaultDownloadImpl.d(DefaultDownloadImpl.java:251)
	at com.just.agentweb.download.DefaultDownloadImpl.a(DefaultDownloadImpl.java:184)
	at com.just.agentweb.download.DefaultDownloadImpl.onDownloadStart(DefaultDownloadImpl.java:144)
	at com.android.webview.chromium.WebViewContentsClientAdapter.onDownloadStart(WebViewContentsClientAdapter.java:503)
	at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:25)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

机型： PRA-ALOOX  android 系统8.0.0

**Comment by zhp475433752** [comment]
我的也报这个空指针异常，你的现在处理好了么？
