### ISSUE TITLE
下载报空指针，出现40次了，麻烦了

### ISSUE THREAD

**Issue by zhp475433752** [Justson/AgentWeb#461]
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.just.agentweb.download.DefaultDownloadImpl$ExtraServiceImpl.getHeaders()' on a null object reference
at com.just.agentweb.download.Downloader.createUrlConnectionAndSettingHeaders(TbsSdkJava:327)

**Comment by Justson** [comment]
#429
