### ISSUE TITLE
启动报错 Unable to get provider com.just.agentweb.AgentWebFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data

### ISSUE THREAD

**Issue by ufohjl** [Justson/AgentWeb#468]
```
java.lang.RuntimeException: Unable to get provider com.just.agentweb.AgentWebFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                      at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:199)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6669)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                   Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                      at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:607)
                      at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
                      at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:391)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
                      at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:193) 
                      at android.app.ActivityThread.main(ActivityThread.java:6669) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

```

**Comment by cc365774016** [comment]
@ufohjl  你是如何解决这个问题的呢
