### ISSUE TITLE
Kotlin使用agentweb引起WebView的onPageStarted中favicon为空导致崩溃

### ISSUE THREAD

**Issue by iOrchid** [Justson/AgentWeb#490]
- 场景：

  kotlin开发环境，使用AgentWeb，在WebActivity的onCreate中，AgentWeb初始配置如下

  ```kotlin
   //初始化AgentWeb对象
          mAgentWeb = AgentWeb.with(this)
              .setAgentWebParent(
                  mLinearLayout, LinearLayout.LayoutParams(
                      ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT
                   )
               )
               .useDefaultIndicator()
               .setWebChromeClient(mWebChromeClient)
               .setWebViewClient(mWebViewClient)//注意这里！！！！！！！！
               .setMainFrameErrorView(R.layout.agentweb_error_page, -1)
               .setSecurityType(AgentWeb.SecurityType.STRICT_CHECK)
   		.setOpenOtherPageWays(DefaultWebClient.OpenOtherPageWays.ASK)//打开其他应用时，弹窗咨询用户是否前往其他应用
               .interceptUnkownUrl() //拦截找不到相关页面的Scheme
               .createAgentWeb()
               .ready()
               .go("http://www.google.com")
  ```

- 问题

  打开`WebActivity`会直接崩溃，错误日志如下

  ```groovy
  java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter favicon
          at com.zhiwei.services.webapp.BaseWebActivity$mWebViewClient$1.onPageStarted(Unknown Source:12)
          at com.just.agentweb.WebViewClientDelegate.onPageStarted(WebViewClientDelegate.java:80)
          at com.just.agentweb.DefaultWebClient.onPageStarted(DefaultWebClient.java:466)
          at xq.b(SourceFile:219)
          at alW.handleMessage(SourceFile:20)
          at android.os.Handler.dispatchMessage(Handler.java:106)
          at android.os.Looper.loop(Looper.java:193)
  ```

  问题清晰描述为在`onPagestarted`函数中`favicon`字段为空，kotlin本身调用时候认为为非空的数据，现在为空，所以引起崩溃。

- 解决方案

  - 如不需要特殊处理，可以移除`setWebViewClient`这个初始化配置

  - 若需要使用`setWebViewClient`,则需要同时设置一个`useMiddlewareWebClient`

    ```kotlin
    .setWEbViewClient(mWebViewClient)
    .useMiddlewareWebClient(object:MiddlewareWebClientBase(){
        //可以抽取出去，定义一个实现类也行，这里使用了匿名内部类
        override fun onPageStarted(view: WebView?, url: String?, favicon: Bitmap?) {
                        //定义一个bitmap，避免favicon为空，引起的崩溃
                        val ff = favicon ?: ImageUtils.drawable2Bitmap(AppUtils.getAppIcon())
                        super.onPageStarted(view, url, ff)
                    }
    })
    ```

  - 修改源码`DefaultWebClient`

    ```java
    @Override
    	public void onPageStarted(WebView view, String url, Bitmap favicon) {
    		//在这里处理favicon为空，defaultWebClient内部有Activity的弱引用
            //可以取Activity获取到resource，来构建一个bitmap给faicon，
            //或者WebIconDatabase.getInstance().open(getDir("icons", MODE_PRIVATE).getPath());设置web的图标
    		if (!mWaittingFinishSet.contains(url)) {
    			mWaittingFinishSet.add(url);
    		}
    		super.onPageStarted(view, url, favicon);
    
    	}
    ```

    

- 原因分析：kotlin语言中若未声明`bitmap:Bitmap?`为可`null`类型，则断定就是非空，所以如果传递的值，是`null`值，就会崩溃。类似Java中`@NonNull`标记，而`AgentWeb`的`DefaultWebClient`、`WebViewClientdelegate`的`onPageStarted`函数，都是`java`文件，里面未做`favicon`的非空判断。（**似乎就是android webview的问题**）

**Comment by ChenJia-X** [comment]
碰到相同问题

**Comment by parcool** [comment]
点赞。

**Comment by 4what2do** [comment]
还是挂了

**Comment by zhiwei1990** [comment]
> v4.1.2的还是挂了

估计是作者并没有修改这个Bug，你可以参照上面的描述，自己处理一下。

**Comment by 4what2do** [comment]
> > v4.1.2的还是挂了
> 
> 估计是作者并没有修改这个Bug，你可以参照上面的描述，自己处理一下。

按照你们讲的设置了useMiddlewareWebClient还是挂了

**Comment by zhiwei1990** [comment]
> > > v4.1.2的还是挂了
> > 
> > 
> > 估计是作者并没有修改这个Bug，你可以参照上面的描述，自己处理一下。
> 
> 按照你们讲的设置了useMiddlewareWebClient还是挂了，你是v4.1.2的吗？

我这边用的也是4.1.2的，你设置useMiddlewareWebClient在onPageStarted中定义bitmap了么，避免favicon为空

**Comment by 4what2do** [comment]
.useMiddlewareWebClient(object : MiddlewareWebClientBase() {
                override fun onPageStarted(view: WebView?, url: String?, favicon: Bitmap?) {
                    val ff = favicon?: activity?.getMyDrawable(R.drawable.ic_launcher_wx_share)?.toBitmap()
                    super.onPageStarted(view, url, ff)
                }
})

**Comment by zhiwei1990** [comment]
> .useMiddlewareWebClient(object : MiddlewareWebClientBase() {
> override fun onPageStarted(view: WebView?, url: String?, favicon: Bitmap?) {
> val ff = favicon?: activity?.getMyDrawable(R.drawable.ic_launcher_wx_share)?.toBitmap()
> super.onPageStarted(view, url, ff)
> }
> })

`val ff = favicon?: activity?.getMyDrawable(R.drawable.ic_launcher_wx_share)?.toBitmap()`你这后版本也就是`:`之后的部分，可能获取的`bitmap`也是`null`。所以保持`ff`必须非空，才可以调用下面的`super`

**Comment by 4what2do** [comment]
喔喔

**Comment by 4what2do** [comment]
webView = AgentWeb.with(this)
            .setAgentWebParent(ll_container as LinearLayout, LinearLayout.LayoutParams(-1, -1))
            .useDefaultIndicator()
            .setWebViewClient(mWebViewClient) //单独配置会出现该问题,需要设置useMiddlewareWebClient https://github.com/Justson/AgentWeb/issues/490
            .useMiddlewareWebClient(object : MiddlewareWebClientBase() {
                override fun onPageStarted(view: WebView?, url: String?, favicon: Bitmap?) {
                    val ff = favicon ?: ImageUtils.drawable2Bitmap(AppUtils.getAppIcon())
//                        ?: activity?.getMyDrawable(R.drawable.ic_launcher_wx_share)?.toBitmap()

                    super.onPageStarted(view, url, ff)
                }

还是报错

**Comment by Cancrileo** [comment]
我用 方法2 还是同样的报错 用方法1就没问题

**Comment by code-rebooter** [comment]
不用搞那么复杂啊 ，直接在favicon  参数后面加个问号就行

**Comment by Justson** [comment]
结论：这不是 AgentWeb 的缺陷，而是 Kotlin 使用方的 override 签名问题。

`WebViewClient#onPageStarted(WebView, String, Bitmap)` 的 `favicon` 参数在 framework 契约中**本身就是可空的** —— 页面开始加载时图标往往还没拿到，此时传入 null 属于正常情况。

Java 没有空安全标注，Kotlin 在 override 时会把它当作平台类型，如果你写成非空 `Bitmap`，编译器会插入 `Intrinsics.checkNotNullParameter` 检查，收到 null 就抛 `NullPointerException`：

```kotlin
// ❌ 崩溃：favicon 声明为非空
override fun onPageStarted(view: WebView?, url: String?, favicon: Bitmap) { }

// ✅ 正确：声明为可空
override fun onPageStarted(view: WebView?, url: String?, favicon: Bitmap?) { }
```

AgentWeb 自身在 `DefaultWebClient#onPageStarted` 中只是把 favicon 透传给下一级，全程没有解引用，因此库这一侧不需要改动。

之前有两个 PR（#1083 / #1086）尝试从库侧处理这个问题，其中 #1083 提议在 null 时填充一张 1×1 占位图 —— 这会破坏「favicon 可空」的平台契约，也会让 `if (favicon != null)` 这类判断永远成立，已说明原因后关闭。

按使用方签名问题关闭此 issue，如果你在正确声明为 `Bitmap?` 后仍然遇到崩溃，欢迎贴出堆栈重开。
