### ISSUE TITLE
下载 doInBackgroud 错误

### ISSUE THREAD

**Issue by ImportEffort** [Justson/AgentWeb#500]
版本4.0.2 
手机型号：Le X620
系统版本：6.0

出错堆栈：

```
java.lang.RuntimeException: An error occurred while executing doInBackground()

	at android.os.AsyncTask$3.done(AsyncTask.java:309)

	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)

	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)

	at java.util.concurrent.FutureTask.run(FutureTask.java:242)

	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

	at java.lang.Thread.run(Thread.java:818)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.just.agentweb.download.DefaultDownloadImpl$ExtraServiceImpl.getHeaders()' on a null object reference

	at com.just.agentweb.download.Downloader.createUrlConnectionAndSettingHeaders(Unknown Source)

	at com.just.agentweb.download.Downloader.doDownload(Unknown Source)

	at com.just.agentweb.download.Downloader.doInBackground(Unknown Source)

	at com.just.agentweb.download.Downloader.doInBackground(Unknown Source)

	at android.os.AsyncTask$2.call(AsyncTask.java:295)

	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

	... 4 more

java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map com.just.agentweb.download.DefaultDownloadImpl$ExtraServiceImpl.getHeaders()' on a null object reference

	at com.just.agentweb.download.Downloader.createUrlConnectionAndSettingHeaders(Unknown Source)

	at com.just.agentweb.download.Downloader.doDownload(Unknown Source)

	at com.just.agentweb.download.Downloader.doInBackground(Unknown Source)

	at com.just.agentweb.download.Downloader.doInBackground(Unknown Source)

	at android.os.AsyncTask$2.call(AsyncTask.java:295)
```
修改建议：DownLoader 327行

`if (null != (mHeaders = mDownloadTask.getExtraServiceImpl().getHeaders()) &&
				!mHeaders.isEmpty()) {`

改为 ->

`if (null != (mDownloadTask.getExtraServiceImpl() !=null && mHeaders = mDownloadTask.getExtraServiceImpl().getHeaders()) &&
				!mHeaders.isEmpty()) {`

**Comment by Justson** [comment]
V4.0.3 fixed
