### ISSUE TITLE
部分手机createAgentWeb时报错

### ISSUE THREAD

**Issue by zhangshijie01** [Justson/AgentWeb#525]
在Fabric崩溃日志查看，大多在Android5.1、5.1.1的手机上会报错误
错误如下：
Caused by android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:146)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
       at android.webkit.WebView.getFactory(WebView.java:2207)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2202)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2261)
       at android.view.View.(View.java:3835)
       at android.view.View.(View.java:3946)
       at android.view.ViewGroup.(ViewGroup.java:513)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java:55)
       at android.webkit.WebView.(WebView.java:556)
       at android.webkit.WebView.(WebView.java:501)
       at android.webkit.WebView.(WebView.java:484)
       at android.webkit.WebView.(WebView.java:471)
       at android.webkit.WebView.(WebView.java:461)
       at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:240)
       at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:181)
       at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:157)
       at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34)
       at com.just.agentweb.AgentWeb.(AgentWeb.java:197)
       at com.just.agentweb.AgentWeb.(AgentWeb.java:43)
       at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:567)
       at com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:499)
       at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:706)

请问是部分机型不适配的原因吗？求解答

**Comment by liungkejin** [comment]
这是系统问题，不是库的问题
