### ISSUE TITLE
Android 9.0 多线程使用相同目录问题

### ISSUE THREAD

**Issue by deng81416754** [Justson/AgentWeb#542]
Android9.0机型上出现 闪退  报上放的错

04-23 19:18:04.657 17580-17580/com.ibgoing E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ibgoing, PID: 17580
 java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
 at com.android.webview.chromium.WebViewChromiumAwInit.startChromiumLocked(WebViewChromiumAwInit.java:63)
     at 
at com.android.webview.chromium.WebViewChromiumAwInitForP.startChromiumLocked(WebViewChromiumAwInitForP.java:3)
  at com.android.webview.chromium.WebViewChromiumAwInit$3.run(WebViewChromiumAwInit.java:3)  at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by deng81416754** [comment]
如果出现同样的问题可以参考 https://blog.csdn.net/lvshuchangyin/article/details/89446629

**Comment by liyujiang-gzu** [comment]
我也遇到，也是搜到的楼上的解决方案：
```text
1、异常日志:Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377

2、异常出现情景:因为Android P行为变更，不可多进程使用同一个目录webView，需要为不同进程webView设置不同目录
3、解决方式：重写项目Application，然后为其它进程webView设置目录
————————————————
版权声明：本文为CSDN博主「erweimaerweima」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/lvshuchangyin/article/details/89446629
```

**Comment by may7be** [comment]
> 如果出现同样的问题可以参考 https://blog.csdn.net/lvshuchangyin/article/details/89446629

在我们的app里，还是有不少崩溃，大部分是NX563J, 还有少量的华为、三星

**Comment by XiaoDon** [comment]
> > 如果出现同样的问题可以参考 https://blog.csdn.net/lvshuchangyin/article/details/89446629
> 
> 在我们的app里，还是有不少崩溃，大部分是NX563J, 还有少量的华为、三星

请问你们解决了吗?是不是用了插件化?

**Comment by deng81416754** [comment]
> > p里，还是有过多崩溃，大部分是NX563J，还有少量的华为，三星
> 
> 请问你们解决了吗？是不是用了插件化？

  if (!"com.yc.kabuqinuo".equals(processName)){//判断不等于默认进程名称 com.yc.kabuqinuo=>要改成自己的项目的包名

**Comment by liyujiang-gzu** [comment]
> > 如果出现同样的问题可以参考 https://blog.csdn.net/lvshuchangyin/article/details/89446629
> 
> 在我们的app里，还是有不少崩溃，大部分是NX563J, 还有少量的华为、三星

已发布的版本4.1.2里还不包括这部分已修复的代码

**Comment by huopochuan** [comment]
> > 如果出现同样的问题可以参考 https://blog.csdn.net/lvshuchangyin/article/details/89446629
> 
> 在我们的app里，还是有不少崩溃，大部分是NX563J, 还有少量的华为、三星

确实大部分都是nx563

**Comment by PONY626** [comment]
我最近发现部分 oppo vivo  还是有这个问题
