### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by AndroidBreathing** [Justson/AgentWeb#556]
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A161847 from pid=21111, uid=10250 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.readException(Parcel.java:1954)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:766)
        at android.content.ContentResolver.query(ContentResolver.java:716)
        at android.content.ContentResolver.query(ContentResolver.java:667)
        at org.chromium.base.ContentUriUtils.isVirtualDocument(ContentUriUtils.java:91)
        at org.chromium.base.ContentUriUtils.getAssetFileDescriptor(ContentUriUtils.java:32)
        at org.chromium.base.ContentUriUtils.openContentUriForRead(ContentUriUtils.java:5)

**Comment by a1336906497** [comment]
你这个uri不对这明显不是文件路径，需要用cursor查询文件

**Comment by zhlofworks** [comment]
遇到同样的问题，在h5中，选择完图片去上传就会报这个错。请问怎么解决的？
我的报错如下：
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaDocumentsProvider uri content://com.android.providers.media.documents/document/image%3A49519 from pid=31464, uid=10383 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

**Comment by AndroidBreathing** [comment]
@zhlofworks 我好几 我用原生搞定的

**Comment by AndroidBreathing** [comment]
@zhlofworks 我着急 后来用原生WebView搞定的

**Comment by zhlofworks** [comment]
好的，多谢。我尝试解决一下

**Comment by zhlofworks** [comment]
@AndroidBreathing 经过测试，发现是FileChooser类中getFileChooserIntent()方法导致的问题，修改如下：
把mIntent.setAction(Intent.ACTION_GET_CONTENT)；
修改成mIntent.setAction(Intent.ACTION_OPEN_DOCUMENT);
可以正常上传

**Comment by AndroidBreathing** [comment]
@zhlofworks 谢谢 回头看看

**Comment by sherry0816** [comment]
缺少了权限
