### ISSUE TITLE
简单使用，报错java.lang.ClassNotFoundException: com.just.agentweb.download.DefaultDownloadImpl

### ISSUE THREAD

**Issue by nihaohebin** [Justson/AgentWeb#560]
java.lang.ClassNotFoundException: com.just.agentweb.download.DefaultDownloadImpl
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:309)
    at java.lang.Class.forName(Class.java:273)
    at com.just.agentweb.AgentWebSettingsImpl.setDownloader(AgentWebSettingsImpl.java:41)

**Comment by Justson** [comment]
忽略异常

**Comment by Jasonono** [comment]
bugly崩溃分析有这个报错

**Comment by Justson** [comment]
` api 'com.download.library:Downloader:4.1.2'// (可选)`
