### ISSUE TITLE
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by manwuyuantao** [Justson/AgentWeb#567]
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    at android.support.v7.app.AppCompatDelegateImplV9.m(AppCompatDelegateImplV9.java:354)
    at android.support.v7.app.AppCompatDelegateImplV9.g(AppCompatDelegateImplV9.java:323)
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
    at android.support.v7.app.ac.setContentView(AppCompatDialog.java:83)
    at android.support.v7.app.AlertController.installContent(AlertController.java:231)
    at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:278)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:610)
    at android.app.Dialog.show(Dialog.java:454)
    at com.just.agentweb.DefaultUIController.onOpenPagePrompt(DefaultUIController.java:86)
    at com.just.agentweb.AgentWebUIControllerImplBase.onOpenPagePrompt(AgentWebUIControllerImplBase.java:45)
    at com.just.agentweb.DefaultWebClient.urlOpenWays(DefaultWebClient.java:261)
    at com.just.agentweb.DefaultWebClient.shouldOverrideUrlLoading(DefaultWebClient.java:225)
    at CU.a(PG:1)
    at kd.b(PG:79)
    at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:150)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:386)
    at android.os.Looper.loop(Looper.java:175)
    at android.app.ActivityThread.main(ActivityThread.java:7593)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by Justson** [comment]
看 README.md
