### ISSUE TITLE
使用的是最新版本。虽然不影响开发，但总是报错

### ISSUE THREAD

**Issue by nihaohebin** [Justson/AgentWeb#574]
java.lang.ClassNotFoundException: com.just.agentweb.download.DefaultDownloadImpl
    at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:309)
     at java.lang.Class.forName(Class.java:273)
     at com.just.agentweb.AgentWebSettingsImpl.setDownloader(AgentWebSettingsImpl.java:41)
     at com.just.agentweb.AgentWeb.ready(AgentWeb.java:437)
     at com.just.agentweb.AgentWeb.access$3100(AgentWeb.java:43)
     at com.just.agentweb.AgentWeb$PreAgentWeb.ready(AgentWeb.java:314)

**Comment by Justson** [comment]
关闭日志
