### ISSUE TITLE
androidx appcompat 1.1.0会报错，低版本系统，目前知道5.1会   android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by nihaohebin** [Justson/AgentWeb#636]

**Comment by Justson** [comment]
日志

**Comment by shuaishuai321** [comment]
[DateTime: 2019-09-19 12:48:59]
[DeviceInfo: ]
  BOARD: msm8952
  BOOTLOADER: unknown
  BRAND: vivo
  CPU_ABI: armeabi-v7a
  CPU_ABI2: armeabi
  DEVICE: PD1602
  DISPLAY: LMY47V release-keys
  FINGERPRINT: vivo/PD1602/PD1602:5.1.1/LMY47V/compiler08121112:user/release-keys
  HARDWARE: qcom
  HOST: compiler025
  ID: LMY47V
  IS_DEBUGGABLE: false
  MANUFACTURER: vivo
  MODEL: vivo X7
  PRODUCT: PD1602
  RADIO: M8939.1020.3
  SERIAL: af33f41a
  SUPPORTED_32_BIT_ABIS: [Ljava.lang.String;@3eecab0c
  SUPPORTED_64_BIT_ABIS: [Ljava.lang.String;@3e2aac55
  SUPPORTED_ABIS: [Ljava.lang.String;@176b766a
  TAG: Build
  TAGS: release-keys
  TIME: 1565579577000
  TYPE: user
  UNKNOWN: unknown
  USER: compiler
  Device Manufacturer: vivo
  Device Model       : vivo X7
  Android Version    : 5.1.1
  Android SDK        : 22
  App VersionName    : 1.6.1
  App VersionCode    : 24
[Excetpion: ]
java.lang.RuntimeException: Unable to start activity ComponentInfo{cardking.rzzh.com/cardking.rzzh.com.webActivity.InvitationCodeActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5418)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:318)
	at android.content.res.VivoResources.getText(VivoResources.java:123)
	at android.content.res.Resources.getString(Resources.java:404)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:694)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:618)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
	at android.webkit.WebView.<init>(WebView.java:554)
	at android.webkit.WebView.<init>(WebView.java:489)
	at android.webkit.WebView.<init>(WebView.java:472)
	at android.webkit.WebView.<init>(WebView.java:459)
	at android.webkit.WebView.<init>(WebView.java:449)
	at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:252)
	at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:191)
	at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:166)
	at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:35)
	at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:205)
	at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:44)
	at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:600)
	at com.just.agentweb.AgentWeb$AgentBuilder.access$4000(AgentWeb.java:527)
	at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:752)
	at com.just.agentweb.use.BaseWebActivity.initView(BaseWebActivity.java:78)
	at cardking.rzzh.com.webActivity.InvitationCodeActivity.initView(InvitationCodeActivity.java:27)
	at com.rnjf.common.base.BaseActivity.onCreate(BaseActivity.java:216)
	at android.app.Activity.performCreate(Activity.java:6083)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
	... 10 more
android.content.res.Resources$NotFoundException: String resource ID #0x2040003
	at android.content.res.Resources.getText(Resources.java:318)
	at android.content.res.VivoResources.getText(VivoResources.java:123)
	at android.content.res.Resources.getString(Resources.java:404)
	at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:694)
	at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:618)
	at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
	at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
	at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
	at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
	at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
	at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
	at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
	at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
	at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
	at android.webkit.WebView.<init>(WebView.java:554)
	at android.webkit.WebView.<init>(WebView.java:489)
	at android.webkit.WebView.<init>(WebView.java:472)
	at android.webkit.WebView.<init>(WebView.java:459)
	at android.webkit.WebView.<init>(WebView.java:449)
	at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:252)
	at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:191)
	at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:166)
	at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:35)
	at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:205)
	at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:44)
	at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:600)
	at com.just.agentweb.AgentWeb$AgentBuilder.access$4000(AgentWeb.java:527)
	at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:752)
	at com.just.agentweb.use.BaseWebActivity.initView(BaseWebActivity.java:78)
	at cardking.rzzh.com.webActivity.InvitationCodeActivity.initView(InvitationCodeActivity.java:27)
	at com.rnjf.common.base.BaseActivity.onCreate(BaseActivity.java:216)
	at android.app.Activity.performCreate(Activity.java:6083)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1115)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2357)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5418)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by StarSpark** [comment]
升级支持androidx后，我也遇到这个问题了。
5.1机型报错 android.content.res.Resources$NotFoundException

**Comment by Merpyzf** [comment]
我也遇到了这个问题 android.content.res.Resources$NotFoundException， 报错的也全部都是5.1的系统

**Comment by moneeWong** [comment]
+1

**Comment by liyujiang-gzu** [comment]
Android 5.1的确会`Resources$NotFoundException: String resource ID #0x2040003`，但Android 7.1正常。
我fork一份迁移到AndroidX，但是Android 5.1仍然会`Resources$NotFoundException: String resource ID #0x2040003`，所以不是因为AndroidX导致的吧

**Comment by moneeWong** [comment]
https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview
网上说是 appcompat:1.1.0的问题 我试了一下换成1.1.0-beta01确实好了

**Comment by liyujiang-gzu** [comment]
正如楼上老铁提供的链接里所言，使用LollipopFixedWebView代替WebView能解决问题

**Comment by liyujiang-gzu** [comment]
经一段时间的验证，用以下关键代码自定义WebView的确能解决：
```java
    private static Context getFixedContext(Context context) {
        if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT < 23) // Android Lollipop 5.0 & 5.1
            return context.createConfigurationContext(new Configuration());
        return context;
    }
```

**Comment by lihaodong** [comment]
我也遇到了这个问题

**Comment by liyujiang-gzu** [comment]
> 我也遇到了这个问题

参见前面提到的解决方案：LollipopFixedWebView

**Comment by hexi** [comment]
我遇到的是vivo手机5.1版本才会出现这个问题，华为、oppo不会，小米没试

**Comment by adarcy** [comment]
> 我遇到的是vivo手机5.1版本才会出现这个问题，华为、oppo不会，小米没试

我这边遇到的崩溃也都是vivo，别的手机没出现

**Comment by alphater** [comment]
> 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> 
> ```java
>     私人 静态 上下文 getFixedContext（语境上下文）{
>          如果（生成。 VERSION 。 SDK_INT  > =  21  &&  生成。 VERSION 。 SDK_INT  <  23）//的Android棒棒糖5.0＆5.1 
>             返回上下文。createConfigurationContext（new  Configuration（））;
>         返回上下文
>     }
> ```

This will cause some js exceptions in the webview

**Comment by liyujiang-gzu** [comment]
> > 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> > ```java
> >     私人 静态 上下文 getFixedContext（语境上下文）{
> >          如果（生成。 VERSION 。 SDK_INT  > =  21  &&  生成。 VERSION 。 SDK_INT  <  23）//的Android棒棒糖5.0＆5.1 
> >             返回上下文。createConfigurationContext（new  Configuration（））;
> >         返回上下文
> >     }
> > ```
> 
> This will cause some js exceptions in the webview

老铁，引起的JS异常能举个例子么，我所用的APP在用这个方案后运行了将近三个月貌似还没遇到问题

**Comment by alphater** [comment]
> > > 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> > > ```java
> > >     私有静态静态某些getFixedContext（语境上下文）{
> > >          如果（生成VERSION。SDK_INT   >  =   21   &&   生成。VERSION。SDK_INT   <   23）//的Android的棒棒糖5.0＆5.1 
> > >             返回上下文.createConfigurationContext（新   配置（））;
> > >         返回部份
> > >     }
> > > ```
> > 
> > 
> > 这将导致webview中的一些js异常
> 
> 老铁，引起的JS异常能举个例子么，我所用的APP在用这个方案后运行了将近三个月貌似还没遇到问题

会导致H5内的选择框无法点击，这是目前遇到的问题。

**Comment by alphater** [comment]
> > > > 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> > > > ```java
> > > >     私有静态静态某些getFixedContext（语境上下文）{
> > > >          如果（生成VERSION。SDK_INT   >  =   21   &&   生成。VERSION。SDK_INT   <   23）//的Android的棒棒糖5.0＆5.1 
> > > >             返回上下文.createConfigurationContext（新   配置（））;
> > > >         返回部份
> > > >     }
> > > > ```
> > > 
> > > 
> > > 这将导致webview中的一些js异常
> > 
> > 
> > 老铁，引起的JS异常能举个例子么，我所用的APP在用这个方案后运行了将近三个月貌似还没遇到问题
> 
> 会导致H5内的选择框无法点击，这是目前遇到的问题。

`  // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133
    @Override
    public void applyOverrideConfiguration(Configuration overrideConfiguration) {
        if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) {
            return;
        }
        super.applyOverrideConfiguration(overrideConfiguration);
    }`
这个方案可以解决无法点击和Resources$NotFoundException的问题，但是不知道会不会有其它影响。

**Comment by SNXJ** [comment]
> > > > > 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> > > > > ```java
> > > > >     私有静态静态某些getFixedContext（语境上下文）{
> > > > >          如果（生成VERSION。SDK_INT   >  =   21   &&   生成。VERSION。SDK_INT   <   23）//的Android的棒棒糖5.0＆5.1 
> > > > >             返回上下文.createConfigurationContext（新   配置（））;
> > > > >         返回部份
> > > > >     }
> > > > > ```
> > > > 
> > > > 
> > > > 这将导致webview中的一些js异常
> > > 
> > > 
> > > 老铁，引起的JS异常能举个例子么，我所用的APP在用这个方案后运行了将近三个月貌似还没遇到问题
> > 
> > 
> > 会导致H5内的选择框无法点击，这是目前遇到的问题。
> 
> ` // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133 @Override public void applyOverrideConfiguration(Configuration overrideConfiguration) { if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) { return; } super.applyOverrideConfiguration(overrideConfiguration); }`
> 这个方案可以解决无法点击和Resources$NotFoundException的问题，但是不知道会不会有其它影响。



> > > > > 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> > > > > ```java
> > > > >     私有静态静态某些getFixedContext（语境上下文）{
> > > > >          如果（生成VERSION。SDK_INT   >  =   21   &&   生成。VERSION。SDK_INT   <   23）//的Android的棒棒糖5.0＆5.1 
> > > > >             返回上下文.createConfigurationContext（新   配置（））;
> > > > >         返回部份
> > > > >     }
> > > > > ```
> > > > 
> > > > 
> > > > 这将导致webview中的一些js异常
> > > 
> > > 
> > > 老铁，引起的JS异常能举个例子么，我所用的APP在用这个方案后运行了将近三个月貌似还没遇到问题
> > 
> > 
> > 会导致H5内的选择框无法点击，这是目前遇到的问题。
> 
> ` // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133 @Override public void applyOverrideConfiguration(Configuration overrideConfiguration) { if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) { return; } super.applyOverrideConfiguration(overrideConfiguration); }`
> 这个方案可以解决无法点击和Resources$NotFoundException的问题，但是不知道会不会有其它影响。



> > > > > 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> > > > > ```java
> > > > >     私有静态静态某些getFixedContext（语境上下文）{
> > > > >          如果（生成VERSION。SDK_INT   >  =   21   &&   生成。VERSION。SDK_INT   <   23）//的Android的棒棒糖5.0＆5.1 
> > > > >             返回上下文.createConfigurationContext（新   配置（））;
> > > > >         返回部份
> > > > >     }
> > > > > ```
> > > > 
> > > > 
> > > > 这将导致webview中的一些js异常
> > > 
> > > 
> > > 老铁，引起的JS异常能举个例子么，我所用的APP在用这个方案后运行了将近三个月貌似还没遇到问题
> > 
> > 
> > 会导致H5内的选择框无法点击，这是目前遇到的问题。
> 
> ` // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133 @Override public void applyOverrideConfiguration(Configuration overrideConfiguration) { if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) { return; } super.applyOverrideConfiguration(overrideConfiguration); }`
> 这个方案可以解决无法点击和Resources$NotFoundException的问题，但是不知道会不会有其它影响。

这样是可以解决崩溃的问题 但是在有些页面会出现白屏的情况

**Comment by alphater** [comment]
> > > > > > 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> > > > > > ```java
> > > > > >     私有静态静态某些getFixedContext（语境上下文）{
> > > > > >          如果（生成VERSION。SDK_INT    >   =    21    &&    生成。VERSION。SDK_INT    <    23）//的的Android的棒棒糖5.0＆5.1 
> > > > > >             返回上下文。createConfigurationContext（新配置（））；
> > > > > >         返回部份
> > > > > >     }
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 这将导致webview中的一些js异常
> > > > 
> > > > 
> > > > 老铁，引起的JS异常能举个例子么，我所用的APP在用这个方案后运行了将近三个月貌似还没遇到问题
> > > 
> > > 
> > > 会导致H5内的选择框无法点击，这是目前遇到的问题。
> > 
> > 
> > ` // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133 @Override public void applyOverrideConfiguration(Configuration overrideConfiguration) { if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) { return; } super.applyOverrideConfiguration(overrideConfiguration); }`
> > 这个方案可以解决无法点击和Resources $ NotFoundException的问题，但是不知道会不会有其他影响。
> 
> > > > > > 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> > > > > > ```java
> > > > > >     私有静态静态某些getFixedContext（语境上下文）{
> > > > > >          如果（生成VERSION。SDK_INT    >   =    21    &&    生成。VERSION。SDK_INT    <    23）//的的Android的棒棒糖5.0＆5.1 
> > > > > >             返回上下文。createConfigurationContext（新配置（））；
> > > > > >         返回部份
> > > > > >     }
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 这将导致webview中的一些js异常
> > > > 
> > > > 
> > > > 老铁，引起的JS异常能举个例子么，我所用的APP在用这个方案后运行了将近三个月貌似还没遇到问题
> > > 
> > > 
> > > 会导致H5内的选择框无法点击，这是目前遇到的问题。
> > 
> > 
> > ` // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133 @Override public void applyOverrideConfiguration(Configuration overrideConfiguration) { if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) { return; } super.applyOverrideConfiguration(overrideConfiguration); }`
> > 这个方案可以解决无法点击和Resources $ NotFoundException的问题，但是不知道会不会有其他影响。
> 
> > > > > > 经批准的验证，用以下关键代码自定义WebView的确能解决方案：
> > > > > > ```java
> > > > > >     私有静态静态某些getFixedContext（语境上下文）{
> > > > > >          如果（生成VERSION。SDK_INT    >   =    21    &&    生成。VERSION。SDK_INT    <    23）//的的Android的棒棒糖5.0＆5.1 
> > > > > >             返回上下文。createConfigurationContext（新配置（））；
> > > > > >         返回部份
> > > > > >     }
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 这将导致webview中的一些js异常
> > > > 
> > > > 
> > > > 老铁，引起的JS异常能举个例子么，我所用的APP在用这个方案后运行了将近三个月貌似还没遇到问题
> > > 
> > > 
> > > 会导致H5内的选择框无法点击，这是目前遇到的问题。
> > 
> > 
> > ` // Workaround appcompat-1.1.0 bug https://issuetracker.google.com/issues/141132133 @Override public void applyOverrideConfiguration(Configuration overrideConfiguration) { if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT <= 25) { return; } super.applyOverrideConfiguration(overrideConfiguration); }`
> > 这个方案可以解决无法点击和Resources $ NotFoundException的问题，但是不知道会不会有其他影响。
> 
> 这样是可以解决崩溃的问题但是在某些页面会出现白屏的情况

所以要权衡应该用哪种方案，或者经过大量测试后再按需决定。

**Comment by zhrxcs** [comment]
> 经一段时间的验证，用以下关键代码自定义WebView的确能解决：
> 
> ```java
>     private static Context getFixedContext(Context context) {
>         if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT < 23) // Android Lollipop 5.0 & 5.1
>             return context.createConfigurationContext(new Configuration());
>         return context;
>     }
> ```

赞同，夜神模拟器部分6.x.x对应5.1.1有同样问题，自定义webview可以解决

**Comment by TmacZhang** [comment]
> 经一段时间的验证，用以下关键代码自定义WebView的确能解决：
> 
> ```java
>     private static Context getFixedContext(Context context) {
>         if (Build.VERSION.SDK_INT >= 21 && Build.VERSION.SDK_INT < 23) // Android Lollipop 5.0 & 5.1
>             return context.createConfigurationContext(new Configuration());
>         return context;
>     }
> ```

我使用了还是会崩溃啊
