### ISSUE TITLE
5.1不兼容bug

### ISSUE THREAD

**Issue by hegaojian** [Justson/AgentWeb#652]
魅族5.1系统，打开B沾视频网页会报错
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:1339)
	at org.chromium.android_webview.DefaultVideoPosterRequestHandler$1.run(DefaultVideoPosterRequestHandler.java:39)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5856)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by badboy-tian** [comment]
为什么关了?  我也遇到这个问题了 怎么解决的

**Comment by badboy-tian** [comment]
@Justson  怎么关闭了呀   我用的最新的4.1.2, 现在也遇到了这个问题 请问怎么解决呢  网页里面的标签是 iframe 不是网上说的video标签

**Comment by ZevShiShi** [comment]
这个问题复写WebChromeClient的getDefaultVideoPoster()方法
        @Override
        public Bitmap getDefaultVideoPoster() {
            try {
                //这个地方是加载h5的视频列表 默认图   点击前的视频图
                return BitmapFactory.decodeResource(BaseApplication.context.getResources(),
                        R.mipmap.wh_login_icon);
            } catch (Exception e) {
                return super.getDefaultVideoPoster();
            }
        }


这样就行了
