### ISSUE TITLE
oppo vivo 5.1 空指针 必现奔溃 求救  

### ISSUE THREAD

**Issue by bannerkun** [Justson/AgentWeb#667]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
    at com.just.agentweb.DefaultDownloadImpl.<init>(DefaultDownloadImpl.java:5)
    at com.just.agentweb.DefaultDownloadImpl.create(DefaultDownloadImpl.java:5)
    at com.just.agentweb.AgentWebSettingsImpl.setDownloader(AgentWebSettingsImpl.java:2)
    at com.just.agentweb.AgentWeb.ready(AgentWeb.java:15)
    at com.just.agentweb.AgentWeb.access$3100(AgentWeb.java:1)
    at com.just.agentweb.AgentWeb$PreAgentWeb.ready(AgentWeb.java:2)

**Comment by bannerkun** [comment]
救救孩子

**Comment by Justson** [comment]
DownloadImpl.getInstance().with(activity.getApplication()); 提前初始化DownloadImpl

**Comment by timenoenough** [comment]
> 救救孩子

你的空指针异常解决了吗...
