### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/webview/chromium/WebViewChromium

### ISSUE THREAD

**Issue by lookballs** [Justson/AgentWeb#686]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/webview/chromium/WebViewChromium;
    at com.android.webview.chromium.WebViewChromiumFactoryProvider.createWebView(PG:218)
    at android.webkit.WebView.ensureProviderCreated(WebView.java:2708)
    at android.webkit.WebView.setOverScrollMode(WebView.java:2773)
    at android.view.View.<init>(View.java:4843)
    at android.view.View.<init>(View.java:5001)
    at android.view.ViewGroup.<init>(ViewGroup.java:662)
    at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
    at android.webkit.WebView.<init>(WebView.java:663)
    at android.webkit.WebView.<init>(WebView.java:608)
    at android.webkit.WebView.<init>(WebView.java:591)
    at android.webkit.WebView.<init>(WebView.java:578)
    at android.webkit.WebView.<init>(WebView.java:568)
    at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:232)
    at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:177)
    at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:154)
    at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34)
    at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:195)
    at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43)
    at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:548)
    at com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:482)
    at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:687)

**Comment by RUDNI** [comment]
设备机型
ONEPLUS A5010
系统版本
9
