### ISSUE TITLE
android.app.ContextImpl cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by xia-weiyang** [Justson/AgentWeb#689]
```
Caused by: java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Activity
        at com.just.agentweb.AgentWebSettingsImpl.setDownloader(AgentWebSettingsImpl.java:39)
        at com.just.agentweb.AgentWeb.ready(AgentWeb.java:437)
        at com.just.agentweb.AgentWeb.access$3100(AgentWeb.java:43)
        at com.just.agentweb.AgentWeb$PreAgentWeb.ready(AgentWeb.java:314)
        at com.zlketang.lib_common.base_ui.WebViewActivity.onCreate(WebViewActivity.java:67)
        at android.app.Activity.performCreate(Activity.java:6092)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2502)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2629) 
        at android.app.ActivityThread.access$800(ActivityThread.java:182) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
        at com.didichuxing.doraemonkit.kit.timecounter.instrumentation.ProxyHandlerCallback.handleMessage(ProxyHandlerCallback.java:38) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5706) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828) 
```

**Comment by xia-weiyang** [comment]
出错代码 在这里
```
	@Override
	public WebListenerManager setDownloader(WebView webView, DownloadListener downloadListener) {
		return super.setDownloader(webView, downloadListener == null ?
				DefaultDownloadImpl.create((Activity) webView.getContext(), webView, mAgentWeb.getPermissionInterceptor()) :
				downloadListener);
	}
```

**Comment by liyujiang-gzu** [comment]
> 出错代码 在这里 android 5.1.1会导致崩溃
> 
> ```
> 	@Override
> 	public WebListenerManager setDownloader(WebView webView, DownloadListener downloadListener) {
> 		return super.setDownloader(webView, downloadListener == null ?
> 				DefaultDownloadImpl.create((Activity) webView.getContext(), webView, mAgentWeb.getPermissionInterceptor()) :
> 				downloadListener);
> 	}
> ```

以前我提过[一个PR，不是已经修复过这个问题](https://github.com/Justson/AgentWeb/pull/655/commits/e06dbcd0c726bc7965d4df9024738417b0b14b6d)了的么：

**Comment by xia-weiyang** [comment]
当时是使用gradle依赖的，确实没你的代码，但最后clone下来，发现是有你的这段代码，估计没法新的版本吧

**Comment by liyujiang-gzu** [comment]
> 当时是使用gradle依赖的，确实没你的代码，但最后clone下来，发现是有你的这段代码，估计没法新的版本吧

我看了，作者还没发布新版本到maven仓库，最新版本的包里还没有那么部分代码。
