### ISSUE TITLE
android 5.1.1

### ISSUE THREAD

**Issue by Dingfeixiang** [Justson/AgentWeb#691]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aisino.xdj/com.aisino.mainlibrary.app.client.view.activity.MainFrameActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
        at android.content.res.Resources.getText(Resources.java:299)
        at android.content.res.Resources.getString(Resources.java:385)
        at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
        at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
        at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
        at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
        at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
        at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
        at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
        at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
        at android.webkit.WebView.<init>(WebView.java:554)
        at android.webkit.WebView.<init>(WebView.java:489)
        at android.webkit.WebView.<init>(WebView.java:472)
        at android.webkit.WebView.<init>(WebView.java:459)
        at android.webkit.WebView.<init>(WebView.java:449)
        at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:232)
        at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:177)
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:154)
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34)
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:195)
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43)
        at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:548)
        at com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:482)
        at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:687)
        at com.aisino.mainlibrary.app.client.view.fragment.company.CompanyFragment.initWebView(CompanyFragment.java:426)
        at com.aisino.mainlibrary.app.client.view.fragment.company.CompanyFragment.initData(CompanyFragment.java:415)
        at com.aisino.toollibrary.app.base.fragment.BaseFragment.onCreateView(BaseFragment.java:74)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
    	at androidx.fragment.app.Frag
具体在
        agentWebView = AgentWeb.with(getActivity())
                .setAgentWebParent(llWeb, new LinearLayout.LayoutParams(-1, -1))//传入AgentWeb 的父控件 ，如果父控件为 RelativeLayout ， 那么第二参数需要传入 RelativeLayout.LayoutParams
                .closeIndicator()// 使用默认进度条
                .setWebChromeClient(new WebChromeClient())
                .setWebViewClient(myWebViewClient)
                .setAgentWebWebSettings(getSettings())
                .createAgentWeb()
                .ready().go(MFUrl.INDEX_NEWS_URL);
createAgentWeb 报错
agentWeb 4.1.2 4.0.2 都出错

**Comment by njhuangzf** [comment]
解决了吗，我也遇得到同样的问题

**Comment by lucky013** [comment]
我也遇到了同样的问题

**Comment by liyujiang-gzu** [comment]
See [PR#655](https://github.com/Justson/AgentWeb/pull/655)
