### ISSUE TITLE
下载时会进入error界面，android 8，10会出现，android 9 不会

### ISSUE THREAD

**Issue by timenoenough** [Justson/AgentWeb#692]
I/ agentweb - WebIndicator: mCurrentProgress:3.55 v:100.0  :-2.55
I/ agentweb - DefaultDesignUIController: mWebParentLayout onMainFrameError:com.just.agentweb.WebParentLayout{e098324 V.E...... ........ 0,0-1080,2268 #7f080121 app:id/web_parent_layout_id}
I/ agentweb - WebParentLayout: mErrorLayoutRes:2131427393
I/ agentweb - DefaultWebClient: onReceivedError:net::ERR_FAILED code:-1
E/ agentweb - DefaultDownloadImpl: performDownload:https://****.pdf exist:false
I/Download-Downloader:  enableProgress:true quickProgress:false
W/System.err: java.lang.NoSuchMethodException: com.just.agentweb.DefaultDownloadImpl$4.onProgress [class java.lang.String, long, long, long]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at com.download.library.Downloader.run(Downloader.java:853)
        at com.download.library.Downloader.downloadInternal(Downloader.java:837)
        at com.download.library.Downloader.download(Downloader.java:815)
        at com.download.library.DownloadImpl.enqueue(DownloadImpl.java:82)
        at com.download.library.ResourceRequest.enqueue(ResourceRequest.java:191)
        at com.just.agentweb.DefaultDownloadImpl.taskEnqueue(DefaultDownloadImpl.java:217)
        at com.just.agentweb.DefaultDownloadImpl.performDownload(DefaultDownloadImpl.java:208)
        at com.just.agentweb.DefaultDownloadImpl.preDownload(DefaultDownloadImpl.java:156)
        at com.just.agentweb.DefaultDownloadImpl.onDownloadStartInternal(DefaultDownloadImpl.java:104)
        at com.just.agentweb.DefaultDownloadImpl$1.run(DefaultDownloadImpl.java:85)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
I/Download-DownloadNotifier:  DownloadNotifier:3
I/Download-DownloadNotifier: buildCancelContent id:3000
I/Download-Downloader: settingHeaders
I/HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
I/Download-Downloader: responseCode:200
I/Download-Downloader: rename download , new file name:(1).pdf
I/Download-Downloader: settingHeaders
I/Download-Downloader: responseCode:200
I/Download-DownloadNotifier: buildCancelContent id:3000

**Comment by MR5356** [comment]
同遇到这个问题，怎么不使用这个下载器而是调用系统的下载呢

**Comment by timenoenough** [comment]
> 同遇到这个问题，怎么不使用这个下载器而是调用系统的下载呢

拦截url 然后处理下载吧...

**Comment by MR5356** [comment]
> > 同遇到这个问题，怎么不使用这个下载器而是调用系统的下载呢
> 
> 拦截url 然后处理下载吧...

找到了重写下载的方法，但是还是有这个error界面，的确是包的一个bug

**Comment by Justson** [comment]
这边尝试没有该问题。

**Comment by timenoenough** [comment]
> 这边尝试没有该问题。

网页实现了下载不过又加载了下载链接，所以出现了error界面。

**Comment by Justson** [comment]
方便把url发一下吗？

**Comment by timenoenough** [comment]
> 方便把url发一下吗？
http://localhost:8090/test_%E4%BD%BF%E3%81%84%E6%96%B9Ver2.0%E7%A4%BE%E5%93%A1%E7%B7%A8.pdf  类似这种

**Comment by Justson** [comment]
内网地址？？  提bug前 先用该机子跑下Sample吧

**Comment by walkthehorizon** [comment]
![Screenshot_20200326_165957_com android permission](https://user-images.githubusercontent.com/11797138/77628821-89b59880-6f83-11ea-8eea-67937a4d22ef.jpg)
Demo也会有这个问题，Android10

**Comment by walkthehorizon** [comment]
随便找个文件直接打开url就能复现
