### ISSUE TITLE
android 5.1 空指针 必现奔溃 求救

### ISSUE THREAD

**Issue by timenoenough** [Justson/AgentWeb#718]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
        at com.just.agentweb.DefaultDownloadImpl.<init>(DefaultDownloadImpl.java:73)
        at com.just.agentweb.DefaultDownloadImpl.create(DefaultDownloadImpl.java:238)
        at com.just.agentweb.AgentWebSettingsImpl.setDownloader(AgentWebSettingsImpl.java:44)
        at com.just.agentweb.AgentWeb.ready(AgentWeb.java:437)
        at com.just.agentweb.AgentWeb.access$3100(AgentWeb.java:43)
        at com.just.agentweb.AgentWeb$PreAgentWeb.ready(AgentWeb.java:314)

**Comment by alphater** [comment]
`    @Override
    public void applyOverrideConfiguration(Configuration overrideConfiguration) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP && Build.VERSION.SDK_INT <= Build.VERSION_CODES.N_MR1) {
            return;
        }
        super.applyOverrideConfiguration(overrideConfiguration);
    }`

**Comment by timenoenough** [comment]
> ` @Override public void applyOverrideConfiguration(Configuration overrideConfiguration) { if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP && Build.VERSION.SDK_INT <= Build.VERSION_CODES.N_MR1) { return; } super.applyOverrideConfiguration(overrideConfiguration); }`

这个是放在哪啊

**Comment by totemtec** [comment]
使用 androidx.appcompat:appcompat:1.2.0-alpha02
参考这个最佳答案：
https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview

**Comment by alphater** [comment]
> > ` @Override public void applyOverrideConfiguration(Configuration overrideConfiguration) { if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP && Build.VERSION.SDK_INT <= Build.VERSION_CODES.N_MR1) { return; } super.applyOverrideConfiguration(overrideConfiguration); }`
> 
> 这个是放在哪啊

webview activity

**Comment by Justson** [comment]
4.1.3 ， 刷新gradle缓存
