### ISSUE TITLE
Android 5.x浏览器webView或者qqX5崩溃，Resources$NotFoundException:String resource ID #0x2040003

### ISSUE THREAD

**Issue by li5201314** [Justson/AgentWeb#732]
升级  androidx.appcompat:appcompat:1.1.0  版本导致,大神们修复下....
崩溃日志如下:
 Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
        at android.content.res.Resources.getText(Resources.java:316)
        at android.content.res.Resources.getString(Resources.java:402)
        at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
        at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
        at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
        at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
        at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
        at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:311)
        at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
        at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:263)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
        at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
        at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
        at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:260)
        at android.webkit.WebView.<init>(WebView.java:554)
        at android.webkit.WebView.<init>(WebView.java:489)
        at android.webkit.WebView.<init>(WebView.java:472)
        at android.webkit.WebView.<init>(WebView.java:459)
        at android.webkit.WebView.<init>(WebView.java:449)
        at com.just.agentweb.DefaultWebCreator.createWebView(DefaultWebCreator.java:232)
        at com.just.agentweb.DefaultWebCreator.createLayout(DefaultWebCreator.java:177)
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:154)
        at com.just.agentweb.DefaultWebCreator.create(DefaultWebCreator.java:34)
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:195)
        at com.just.agentweb.AgentWeb.<init>(AgentWeb.java:43)
        at com.just.agentweb.AgentWeb$AgentBuilder.buildAgentWeb(AgentWeb.java:548)
        at com.just.agentweb.AgentWeb$AgentBuilder.access$3700(AgentWeb.java:482)
        at com.just.agentweb.AgentWeb$CommonBuilder.createAgentWeb(AgentWeb.java:687)
        at com.xxx.webviewtest.WebviewActivity.initWebView(WebviewActivity.java:104)
        at com.xxx.webviewtest.WebviewActivity.onCreate(WebviewActivity.java:75)
        at android.app.Activity.performCreate(Activity.java:6222)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5280) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by ccflyy** [comment]
用最新版androidx，androidx.appcompat:appcompat:1.2.0-alpha02

**Comment by 748297973** [comment]
@ccflyy androidx.appcompat:appcompat:1.2.0-alpha02升级这个版本就解决了吗

**Comment by li5201314** [comment]
> 用最新版androidx，androidx.appcompat:appcompat:1.2.0-alpha02

可以了.

**Comment by li5201314** [comment]
收到,已测试可以



在 2020-03-04 11:31:37，"ccflyy" <notifications@github.com> 写道：

用最新版androidx，androidx.appcompat:appcompat:1.2.0-alpha02

**Comment by li5201314** [comment]
升级后解决



在 2020-03-10 20:41:34，"748297973" <notifications@github.com> 写道：

@ccflyy androidx.appcompat:appcompat:1.2.0-alpha02升级这个版本就解决了吗

**Comment by AnJiuZhe** [comment]
项目不能接AndroidX，support包如何解决呢？
