### ISSUE TITLE
vue用的axios，下载文件出现如下错误，浏览器下载是OK的；blob url

### ISSUE THREAD

**Issue by jentzsch** [Justson/AgentWeb#745]
I/Download-Downloader:  enableProgress:true quickProgress:false
W/System.err: java.lang.NoSuchMethodException: com.just.agentweb.DefaultDownloadImpl$4.onProgress [class java.lang.String, long, long, long]
W/System.err:     at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at com.download.library.Downloader.run(Downloader.java:853)
W/System.err:     at com.download.library.Downloader.downloadInternal(Downloader.java:837)
        at com.download.library.Downloader.download(Downloader.java:815)
        at com.download.library.DownloadImpl.enqueue(DownloadImpl.java:82)
        at com.download.library.ResourceRequest.enqueue(ResourceRequest.java:191)
        at com.just.agentweb.DefaultDownloadImpl.taskEnqueue(DefaultDownloadImpl.java:232)
        at com.just.agentweb.DefaultDownloadImpl.performDownload(DefaultDownloadImpl.java:223)
W/System.err:     at com.just.agentweb.DefaultDownloadImpl.preDownload(DefaultDownloadImpl.java:171)
        at com.just.agentweb.DefaultDownloadImpl.onDownloadStartInternal(DefaultDownloadImpl.java:119)
        at com.just.agentweb.DefaultDownloadImpl$1.run(DefaultDownloadImpl.java:100)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
        at com.download.library.Runtime.createFile(Runtime.java:176)
        at com.download.library.Runtime.uniqueFile(Runtime.java:292)
        at com.download.library.Downloader.onPreExecute(Downloader.java:199)
W/System.err:     at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:708)
        at com.download.library.Downloader.run(Downloader.java:865)
        at com.download.library.Downloader.downloadInternal(Downloader.java:837)
        at com.download.library.Downloader.download(Downloader.java:815)
        at com.download.library.DownloadImpl.enqueue(DownloadImpl.java:82)
        at com.download.library.ResourceRequest.enqueue(ResourceRequest.java:191)
        at com.just.agentweb.DefaultDownloadImpl.taskEnqueue(DefaultDownloadImpl.java:232)
        at com.just.agentweb.DefaultDownloadImpl.performDownload(DefaultDownloadImpl.java:223)
        at com.just.agentweb.DefaultDownloadImpl.preDownload(DefaultDownloadImpl.java:171)
        at com.just.agentweb.DefaultDownloadImpl.onDownloadStartInternal(DefaultDownloadImpl.java:119)
        at com.just.agentweb.DefaultDownloadImpl$1.run(DefaultDownloadImpl.java:100)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
    java.lang.RuntimeException: target file can't be created . 
        at com.download.library.Downloader.onPreExecute(Downloader.java:216)
        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:708)
        at com.download.library.Downloader.run(Downloader.java:865)
        at com.download.library.Downloader.downloadInternal(Downloader.java:837)
        at com.download.library.Downloader.download(Downloader.java:815)
        at com.download.library.DownloadImpl.enqueue(DownloadImpl.java:82)
        at com.download.library.ResourceRequest.enqueue(ResourceRequest.java:191)
W/System.err:     at com.just.agentweb.DefaultDownloadImpl.taskEnqueue(DefaultDownloadImpl.java:232)
        at com.just.agentweb.DefaultDownloadImpl.performDownload(DefaultDownloadImpl.java:223)
        at com.just.agentweb.DefaultDownloadImpl.preDownload(DefaultDownloadImpl.java:171)
        at com.just.agentweb.DefaultDownloadImpl.onDownloadStartInternal(DefaultDownloadImpl.java:119)
        at com.just.agentweb.DefaultDownloadImpl$1.run(DefaultDownloadImpl.java:100)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by jentzsch** [comment]
问题大概定位在webview 无法解析 blob url  求大神破解

**Comment by KAICW** [comment]
也遇到同样问题，楼主有没有解决？
