### ISSUE TITLE
最新版本4.1.3，在安卓5.1的版本上点击进去崩溃

### ISSUE THREAD

**Issue by wkm0214** [Justson/AgentWeb#793]
Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
        at com.just.agentweb.DefaultDownloadImpl.<init>(DefaultDownloadImpl.java:74)
        at com.just.agentweb.DefaultDownloadImpl.create(DefaultDownloadImpl.java:244)
        at com.just.agentweb.AgentWebSettingsImpl.setDownloader(AgentWebSettingsImpl.java:44)
        at com.just.agentweb.AgentWeb.ready(AgentWeb.java:437)
        at com.just.agentweb.AgentWeb.access$3100(AgentWeb.java:43)
        at com.just.agentweb.AgentWeb$PreAgentWeb.ready(AgentWeb.java:314)

**Comment by Justson** [comment]
刷新下gradle cache
