### ISSUE TITLE
java.lang.NullPointerException | WebSettings.getForceDark()

### ISSUE THREAD

**Issue by xiaoxiaohua333** [Justson/AgentWeb#811]
### AgentWeb 4.1.3

<pre name="code" class="java">
　Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.webkit.WebSettings.getForceDark()' on a null object reference
       at android.webkit.WebView.updateHwForceDark(WebView.java:2643)
       at android.webkit.WebView.onAttachedToWindow(WebView.java:2625)
       at android.view.View.dispatchAttachedToWindow(View.java:19759)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3596)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3603)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2229)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1879)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8170)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
       at android.view.Choreographer.doCallbacks(Choreographer.java:875)
       at android.view.Choreographer.doFrame(Choreographer.java:776)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8347)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
</pre>

**Comment by Justson** [comment]
这是 Android 10 时期系统 WebView 的框架缺陷，不是 AgentWeb 引入的。

堆栈上没有任何 AgentWeb 代码：

```
WebView.updateHwForceDark(WebView.java:2643)
WebView.onAttachedToWindow(WebView.java:2625)
```

`updateHwForceDark` 内部调用 `getSettings().getForceDark()`，而在部分厂商（华为居多）的 Android 10 WebView 实现中，`getSettings()` 在 `onAttachedToWindow` 时可能尚未就绪而返回 null。这是 WebView 自身的时序问题。

该问题随 WebView 版本迭代已基本绝迹，本 issue 基于 2020 年的 4.1.3。以「框架缺陷 + 当前版本无法复现」关闭。

如果在新版本上仍然遇到，欢迎带上 WebView 版本号重开。
