### ISSUE TITLE
手机内没有安装任何能响应对应Intent 的应用的时候，4.1.4出现No Activity found to handle Intent 

### ISSUE THREAD

**Issue by ppg408331701** [Justson/AgentWeb#873]
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.gxrcw.activity.DownloadFileProvider/download/fa14bae612794a2452e22ca6931ec3a4/1.广西壮族自治区血液中心2020年度公开招聘工作人员岗位信息表.doc typ=application/vnd.ms-word flg=0x10000001 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2120)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1746)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1039)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1000)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
	at com.download.library.DownloadSubmitterImpl$DownloadTaskOver$1.run(DownloadSubmitterImpl.java:294)
	at com.queue.library.BlockingRunnable.run(BlockingRunnable.java:38)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8347)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

百度移动统计出现的bug日志
华为P30
Android 10.0
AgentWeb版本号：4.1.4

**Comment by ppg408331701** [comment]
复现了，如果手机内没有安装任何能响应doc的Intent 的软件，就会出现这个错误。是否可以在跳转前判断一下，或者用trycatch包裹住这个代码块

**Comment by Justson** [comment]
确实存在该bug

**Comment by Justson** [comment]
谢谢反馈
