### ISSUE TITLE
demo中webview独立进程例子在android10上崩溃，其他例子正常

### ISSUE THREAD

**Issue by VioletNight** [Justson/AgentWeb#880]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.violetnight.violetnight/com.violetnight.violetnight.ui.activity.other.web.activity.RemoteWebViewActivity}: android.view.InflateException: Binary XML file line #10 in com.violetnight.violetnight:layout/other_fragment_twk_web: Binary XML file line #10 in com.violetnight.violetnight:layout/other_fragment_twk_web: Error inflating class android.webkit.WebView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3324)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3473)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2060)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7619)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.view.InflateException: Binary XML file line #10 in com.violetnight.violetnight:layout/other_fragment_twk_web: Binary XML file line #10 in com.violetnight.violetnight:layout/other_fragment_twk_web: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #10 in com.violetnight.violetnight:layout/other_fragment_twk_web: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createView(LayoutInflater.java:780)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:934)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:954)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at com.violetnight.violetnight.ui.activity.other.web.widget.WebLayout.<init>(WebLayout.java:28)
	at com.violetnight.violetnight.ui.activity.other.web.base.BaseWebActivity.onCreate(BaseWebActivity.java:78)
	at com.violetnight.violetnight.ui.activity.other.web.activity.RemoteWebViewActivity.onCreate(RemoteWebViewActivity.java:27)
	at android.app.Activity.performCreate(Activity.java:7894)
	at android.app.Activity.performCreate(Activity.java:7881)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3299)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3473)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2060)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7619)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.violetnight.violetnight:web (pid 14346), lock owner com.violetnight.violetnight (pid 10074)
	at org.chromium.android_webview.AwData

**Comment by AdminQQZ** [comment]
同上
![QQ截图20201118182506](https://user-images.githubusercontent.com/12959954/99518350-67b5ce00-29cb-11eb-9e32-3e7b6b6ee4a0.png)
