### ISSUE TITLE
java.lang.IllegalStateException: Unable to create layer for NestedScrollAgentWebView

### ISSUE THREAD

**Issue by laychv** [Justson/AgentWeb#909]
java.lang.IllegalStateException: Unable to create layer for NestedScrollAgentWebView, size 1080x23544 exceeds max size 16384
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:139)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by javakam** [comment]
模拟器Android6.0 API23 出现同样的问题, 不知道是不是模拟器的缘故
