### ISSUE TITLE
Sample中的IPC WebView独立进程必现Crash

### ISSUE THREAD

**Issue by Hackergeek** [Justson/AgentWeb#914]
![image](https://user-images.githubusercontent.com/9377994/119306266-7fcd1980-bc9c-11eb-8543-801b36c2daba.png)
## Crash日志
2021-05-24 14:25:51.996 23790-23790/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.just.agentweb.sample:web, PID: 23790
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.just.agentweb.sample/com.just.agentweb.sample.activity.RemoteWebViewActivity}: android.view.InflateException: Binary XML file line #17 in com.just.agentweb.sample:layout/fragment_twk_web: Binary XML file line #17 in com.just.agentweb.sample:layout/fragment_twk_web: Error inflating class android.webkit.WebView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3898)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: android.view.InflateException: Binary XML file line #17 in com.just.agentweb.sample:layout/fragment_twk_web: Binary XML file line #17 in com.just.agentweb.sample:layout/fragment_twk_web: Error inflating class android.webkit.WebView
     Caused by: android.view.InflateException: Binary XML file line #17 in com.just.agentweb.sample:layout/fragment_twk_web: Error inflating class android.webkit.WebView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:864)
        at android.view.LayoutInflater.createView(LayoutInflater.java:786)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:91)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:940)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:960)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1014)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
        at com.just.agentweb.sample.widget.WebLayout.<init>(WebLayout.java:47)
        at com.just.agentweb.sample.activity.BaseWebActivity.onCreate(BaseWebActivity.java:77)
        at com.just.agentweb.sample.activity.RemoteWebViewActivity.onCreate(RemoteWebViewActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:8121)
        at android.app.Activity.performCreate(Activity.java:8109)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3871)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
2021-05-24 14:25:51.997 23790-23790/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.just.agentweb.sample:web (pid 23790), lock owner  unknown
        at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle.aab-stable-438910533:27)
        at sp0.j(chromium-TrichromeWebViewGoogle.aab-stable-438910533:31)
        at sp0.b(chromium-TrichromeWebViewGoogle.aab-stable-438910533:22)
        at sp0.l(chromium-TrichromeWebViewGoogle.aab-stable-438910533:2)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.g(chromium-TrichromeWebViewGoogle.aab-stable-438910533:2)
        at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle.aab-stable-438910533:14)
        at android.webkit.WebView.<init>(WebView.java:445)
        at android.webkit.WebView.<init>(WebView.java:367)
        at android.webkit.WebView.<init>(WebView.java:350)
        at android.webkit.WebView.<init>(WebView.java:337)
        	... 33 more
## 造成Crash原因

Android9.0之后不同进程的Webview不允许使用同一个目录存储数据，可以通过                    WebView.setDataDirectorySuffix(processName)方法给不同进程的WebView设置不同的数据存储目录。但是示例代码中的WebLayout中的WebView创建时机早于DefaultWebCreator的Create方法，导致出现该异常。
![image](https://user-images.githubusercontent.com/9377994/119306180-64faa500-bc9c-11eb-8e3a-120523e15441.png)
![image](https://user-images.githubusercontent.com/9377994/119306492-d2a6d100-bc9c-11eb-988c-3d7d298c0266.png)

**Comment by Hackergeek** [comment]
## 解决办法
[参考链接](https://www.jianshu.com/p/eccfda6f39c9)
![image](https://user-images.githubusercontent.com/9377994/119307106-bc4d4500-bc9d-11eb-8715-77162dc1780a.png)
