### ISSUE TITLE
.ready()报错，无法启动Activity

### ISSUE THREAD

**Issue by adymilk** [Justson/AgentWeb#94]
FATAL EXCEPTION: main

**Comment by Justson** [comment]
贴一下代码以及错误日志吗？

**Comment by adymilk** [comment]
报错位于 at com.adymilk.simplebrowser.MainActivity.onCreate(MainActivity.java:34)

34行代码是** .ready()**

整体代码如下：


public class MainActivity extends AppCompatActivity {
    private AgentWeb mAgentWeb;
    private LinearLayout mLinearLayout;
    private TextView mTitleTextView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mTitleTextView = (TextView) findViewById(R.id.mTitleTextView);

//        LinearLayout mLinearLayout = (LinearLayout) findViewById(R.id.mLinearLayout);

        mAgentWeb = AgentWeb.with(this)//传入Activity
                .setAgentWebParent(mLinearLayout, new LinearLayout.LayoutParams(-1, -1))//传入AgentWeb 的父控件 ，如果父控件为 RelativeLayout ， 那么第二参数需要传入 RelativeLayout.LayoutParams ,第一个参数和第二个参数应该对应。
                .useDefaultIndicator()// 使用默认进度条
                .defaultProgressBarColor() // 使用默认进度条颜色
                .setReceivedTitleCallback(mCallback) //设置 Web 页面的 title 回调
                .createAgentWeb()//
                .ready()
                .go("http://www.jd.com");
    }
    private ChromeClientCallbackManager.ReceivedTitleCallback mCallback = new ChromeClientCallbackManager.ReceivedTitleCallback() {
        @Override
        public void onReceivedTitle(WebView view, String title) {
            if (mTitleTextView != null)
                mTitleTextView.setText(title);
        }
    };

**Comment by Justson** [comment]
能贴全错误日志吗？

**Comment by adymilk** [comment]
``FATAL EXCEPTION: main
                                                                         Process: com.adymilk.simplebrowser, PID: 1857
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adymilk.simplebrowser/com.adymilk.simplebrowser.MainActivity}: java.lang.SecurityException: ConnectivityService: Neither user 10440 nor current process has android.permission.ACCESS_NETWORK_STATE.
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2853)
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6369)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                          Caused by: java.lang.SecurityException: ConnectivityService: Neither user 10440 nor current process has android.permission.ACCESS_NETWORK_STATE.
                                                                             at android.os.Parcel.readException(Parcel.java:1684)
                                                                             at android.os.Parcel.readException(Parcel.java:1637)
                                                                             at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1200)
                                                                             at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:773)
                                                                             at com.just.library.AgentWebUtils.checkNetwork(AgentWebUtils.java:123)
                                                                             at com.just.library.WebDefaultSettingsManager.settings(WebDefaultSettingsManager.java:48)
                                                                             at com.just.library.WebDefaultSettingsManager.toSetting(WebDefaultSettingsManager.java:36)
                                                                             at com.just.library.AgentWeb.ready(AgentWeb.java:282)
                                                                             at com.just.library.AgentWeb.access$5000(AgentWeb.java:40)
                                                                             at com.just.library.AgentWeb$PreAgentWeb.ready(AgentWeb.java:513)
                                                                             at com.adymilk.simplebrowser.MainActivity.onCreate(MainActivity.java:34)
                                                                             at android.app.Activity.performCreate(Activity.java:6760)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2720)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2853) 
                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6369) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Justson** [comment]
`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"></uses-permission>`
