### ISSUE TITLE
点击选择相册奔溃，已经使用最新代码

### ISSUE THREAD

**Issue by yuekong** [Justson/AgentWeb#953]
android：三星s60 系统 11

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66132, result=0, data=null} to activity {com.just.agentweb.sample/com.just.agentweb.sample.activity.WebActivity}: java.lang.IllegalStateException: showFileChooser result was already called
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5506)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5547)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
     Caused by: java.lang.IllegalStateException: showFileChooser result was already called
        at UB0.onReceiveValue(Unknown Source:40)
        at com.just.agentweb.filechooser.FileChooser.cancel(FileChooser.java:486)
        at com.just.agentweb.filechooser.FileChooser.onIntentResult(FileChooser.java:429)
        at com.just.agentweb.filechooser.FileChooser$2.onChoiceResult(FileChooser.java:251)
        at com.just.agentweb.AgentActionFragment.chooserActionCallback(AgentActionFragment.java:138)
        at com.just.agentweb.AgentActionFragment.onActivityResult(AgentActionFragment.java:149)
        at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:160)
        at com.just.agentweb.sample.activity.BaseWebActivity.onActivityResult(BaseWebActivity.java:175)
        at android.app.Activity.dispatchActivityResult(Activity.java:8541)

**Comment by Justson** [comment]
感谢反馈

**Comment by Justson** [comment]
是用Demo代码?

**Comment by Justson** [comment]
Demo 测试，是没问题的

**Comment by yuekong** [comment]
> Demo 测试，是没问题的

我用的是自定义的 url 地址测试：https://auto-static.aigostar.com/h5/#/helpCenter?countryCode=CN&language=zh
但是 AgentWebFragment 必须加上ua:
   mAgentWeb.getWebCreator().getWebView().setOverScrollMode(WebView.OVER_SCROLL_NEVER);
   String ua = mAgentWeb.getAgentWebSettings().getWebSettings().getUserAgentString();
  mAgentWeb.getAgentWebSettings().getWebSettings().setUserAgentString(ua + "aigosmartapp");

麻烦帮忙测试下 会存在奔溃现象
