### ISSUE TITLE
androidx 版本依赖有问题,  AgentWebFileProvider 依赖的是 support 的provider

### ISSUE THREAD

**Issue by hsoftxl** [Justson/AgentWeb#955]
Process: com.download.sample, PID: 21081
    java.lang.RuntimeException: Unable to get provider com.just.agentweb.AgentWebFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.just.agentweb.AgentWebFileProvider" on path: DexPathList[[zip file "/data/app/~~CRJq5uDi-3FeQi-89Ahg0g==/com.download.sample-2-9RuQhRVSfXEVujp7Vaeg==/base.apk"],nativeLibraryDirectories=[/data/app/~~CRJq5uDi-3FeQi-89Ahg0g==/com.download.sample-2-9RuQhRVSfXEVujp7Vaeg==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7800)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7306)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7200)
        at android.app.ActivityThread.access$1500(ActivityThread.java:269)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8215)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.just.agentweb.AgentWebFileProvider" on path: DexPathList[[zip file "/data/app/~~CRJq5uDi-3FeQi-89Ahg0g==/com.download.sample-2-9RuQhRVSfXEVujp7Vaeg==/base.apk"],nativeLibraryDirectories=[/data/app/~~CRJq5uDi-3FeQi-89Ahg0g==/com.download.sample-2-9RuQhRVSfXEVujp7Vaeg==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7784)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7306) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7200) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:269) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:257) 
        at android.app.ActivityThread.main(ActivityThread.java:8215) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 14 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/~~CRJq5uDi-3FeQi-89Ahg0g==/com.download.sample-2-9RuQhRVSfXEVujp7Vaeg==/base.apk"],nativeLibraryDirectories=[/data/app/~~CRJq5uDi-3FeQi-89Ahg0g==/com.download.sample-2-9RuQhRVSfXEVujp7Vaeg==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 17 more

**Comment by Justson** [comment]
```
implementation 'com.github.Justson.AgentWeb:agentweb-core:v5.0.0-alpha.1-androidx' // (必选)
implementation 'com.github.Justson.AgentWeb:agentweb-filechooser:v5.0.0-alpha.1-androidx' // (可选)
implementation 'com.github.Justson:Downloader:v5.0.0-androidx' // (可选)
```

**Comment by wziwen** [comment]
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/4904096/156694138-010c909a-13f7-415b-903b-f505dbb5b838.png">
问题依旧存在。代码里也的确依赖的是 android.support.v4.content.FileProvider。   

解决办法：  
在 gradle.properties 文件添加下面的配置，打包过程会自动把v4的依赖改成androidx
```
android.enableJetifier=true
```
参考： https://stackoverflow.com/questions/52033810/can-i-use-library-that-used-android-support-with-androidx-projects

**Comment by KoreaHank** [comment]
问题屏蔽掉了，但是最新版本问题还是存在，并没有解决，源代码androidx还是用的support

**Comment by shiheting** [comment]
问题没有解决
