### ISSUE TITLE
h5页面又导出excle，点击导出报错

### ISSUE THREAD

**Issue by lieweisi** [Justson/AgentWeb#958]
2021-12-14 15:31:15.139 761-800/system_process D/InputReader: xby----->ScreenTouch getDeviceName()
2021-12-14 15:31:15.140 761-800/system_process D/InputDispatcher: xiangrong notifyMotion isFound 0 0
2021-12-14 15:31:15.292 761-800/system_process D/InputReader: xby----->ScreenTouch getDeviceName()
2021-12-14 15:31:15.292 761-800/system_process D/InputDispatcher: xiangrong notifyMotion isFound 0 0
2021-12-14 15:31:19.855 14840-15264/com.rykj.yjh W/System.err: java.lang.NoSuchMethodException: onProgress [class java.lang.String, long, long, long]
2021-12-14 15:31:19.855 14840-15264/com.rykj.yjh W/System.err:     at java.lang.Class.getMethod(Class.java:1981)
2021-12-14 15:31:19.855 14840-15264/com.rykj.yjh W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:1960)
2021-12-14 15:31:19.855 14840-15264/com.rykj.yjh W/System.err:     at com.download.library.DownloadSubmitterImpl$DownloadStartTask.run(DownloadSubmitterImpl.java:142)
2021-12-14 15:31:19.855 14840-15264/com.rykj.yjh W/System.err:     at com.download.library.DownloadSubmitterImpl$1.run(DownloadSubmitterImpl.java:93)
2021-12-14 15:31:19.855 14840-15264/com.rykj.yjh W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2021-12-14 15:31:19.855 14840-15264/com.rykj.yjh W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2021-12-14 15:31:19.855 14840-15264/com.rykj.yjh W/System.err:     at java.lang.Thread.run(Thread.java:761)
2021-12-14 15:31:19.876 14840-15264/com.rykj.yjh W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
2021-12-14 15:31:19.877 14840-15264/com.rykj.yjh W/System.err:     at com.download.library.Runtime.createFile(Runtime.java:183)
2021-12-14 15:31:19.877 14840-15264/com.rykj.yjh W/System.err:     at com.download.library.Runtime.uniqueFile(Runtime.java:305)
2021-12-14 15:31:19.877 14840-15264/com.rykj.yjh W/System.err:     at com.download.library.DownloadSubmitterImpl$DownloadStartTask.run(DownloadSubmitterImpl.java:157)
2021-12-14 15:31:19.877 14840-15264/com.rykj.yjh W/System.err:     at com.download.library.DownloadSubmitterImpl$1.run(DownloadSubmitterImpl.java:93)
2021-12-14 15:31:19.877 14840-15264/com.rykj.yjh W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2021-12-14 15:31:19.877 14840-15264/com.rykj.yjh W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2021-12-14 15:31:19.877 14840-15264/com.rykj.yjh W/System.err:     at java.lang.Thread.run(Thread.java:761)
2021-12-14 15:31:19.877 14840-15264/com.rykj.yjh W/System.err: java.lang.RuntimeException: target file can't be created . 
2021-12-14 15:31:19.878 14840-15264/com.rykj.yjh W/System.err:     at com.download.library.DownloadSubmitterImpl$DownloadStartTask.run(DownloadSubmitterImpl.java:174)
2021-12-14 15:31:19.878 14840-15264/com.rykj.yjh W/System.err:     at com.download.library.DownloadSubmitterImpl$1.run(DownloadSubmitterImpl.java:93)
2021-12-14 15:31:19.878 14840-15264/com.rykj.yjh W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2021-12-14 15:31:19.878 14840-15264/com.rykj.yjh W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2021-12-14 15:31:19.878 14840-15264/com.rykj.yjh W/System.err:     at java.lang.Thread.run(Thread.java:761)
2021-12-14 15:31:19.878 14840-15264/com.rykj.yjh E/CrashReport: Java Crash Happen cause by Thread-27(949)
2021-12-14 15:31:19.917 14840-15264/com.rykj.yjh I/CrashReport: user log size:0
2021-12-14 15:31:19.934 14840-15264/com.rykj.yjh E/CrashReport: stack frame :5, has cause false
2021-12-14 15:31:19.936 14840-15264/com.rykj.yjh E/CrashReport: #++++++++++Record By Bugly++++++++++#
2021-12-14 15:31:19.936 14840-15264/com.rykj.yjh E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
2021-12-14 15:31:19.936 14840-15264/com.rykj.yjh E/CrashReport: # PKG NAME: com.rykj.yjh
2021-12-14 15:31:19.937 14840-15264/com.rykj.yjh E/CrashReport: # APP VER: 1.6.1
2021-12-14 15:31:19.937 14840-15264/com.rykj.yjh E/CrashReport: # SDK VER: 4.0.0-4.0.0
2021-12-14 15:31:19.937 14840-15264/com.rykj.yjh E/CrashReport: # LAUNCH TIME: 2021-12-14 15:29:51
2021-12-14 15:31:19.937 14840-15264/com.rykj.yjh E/CrashReport: # CRASH TYPE: JAVA_CRASH
2021-12-14 15:31:19.938 14840-15264/com.rykj.yjh E/CrashReport: # CRASH TIME: 2021-12-14 15:31:19
2021-12-14 15:31:19.938 14840-15264/com.rykj.yjh E/CrashReport: # CRASH PROCESS: com.rykj.yjh
2021-12-14 15:31:19.940 14840-15264/com.rykj.yjh E/CrashReport: # CRASH THREAD: Thread-27
2021-12-14 15:31:19.941 14840-15264/com.rykj.yjh E/CrashReport: # REPORT ID: a714742d-46e8-4338-af8f-d241ba08ca2d
2021-12-14 15:31:19.941 14840-15264/com.rykj.yjh E/CrashReport: # CRASH DEVICE: D2_d UNROOT
2021-12-14 15:31:19.941 14840-15264/com.rykj.yjh E/CrashReport: # RUNTIME AVAIL RAM:1180303360 ROM:3768467456 SD:3768467456
2021-12-14 15:31:19.943 14840-15264/com.rykj.yjh E/CrashReport: # RUNTIME TOTAL RAM:2095824896 ROM:4485410816 SD:4485410816
2021-12-14 15:31:19.943 14840-15264/com.rykj.yjh E/CrashReport: # CRASH STACK: 
2021-12-14 15:31:19.944 14840-15264/com.rykj.yjh E/CrashReport: java.lang.RuntimeException: target file can't be created . 
        at com.download.library.DownloadSubmitterImpl$DownloadStartTask.run(DownloadSubmitterImpl.java:174)
        at com.download.library.DownloadSubmitterImpl$1.run(DownloadSubmitterImpl.java:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2021-12-14 15:31:19.944 14840-15264/com.rykj.yjh E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

**Comment by Justson** [comment]
暂时不支持data协议
