### ISSUE TITLE
target file can't be created .

### ISSUE THREAD

**Issue by lieweisi** [Justson/AgentWeb#959]
java.lang.RuntimeException: target file can't be created . 
        at com.download.library.DownloadSubmitterImpl$DownloadStartTask.run(DownloadSubmitterImpl.java:174)
        at com.download.library.DownloadSubmitterImpl$1.run(DownloadSubmitterImpl.java:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by Justson** [comment]
什么版本呢?

**Comment by lieweisi** [comment]
这是我用的: "agentweb":"com.github.Justson.AgentWeb:agentweb-core:v5.0.0-alpha"
            "filechooser":"com.github.Justson.AgentWeb:agentweb-filechooser:v5.0.0-alpha",
            "Downloader":"com.github.Justson:Downloader:v5.0.0",
测试url地址:https://login.yjhpos.com/#/login?account=lq1125&pwd=112233&isandroid=1&empcode=点击里面的商品，等商品加载出来后，在点击导出就会报这个错误。Android版本7.1.2

**Comment by lieweisi** [comment]
这是我用的: "agentweb":"com.github.Justson.AgentWeb:agentweb-core:v5.0.0-alpha"
            "filechooser":"com.github.Justson.AgentWeb:agentweb-filechooser:v5.0.0-alpha",
            "Downloader":"com.github.Justson:Downloader:v5.0.0",
测试url地址:https://login.yjhpos.com/#/login?account=lq1125&pwd=112233&isandroid=1&empcode=点击里面的商品，等商品加载出来后，在点击导出就会报这个错误。Android版本7.1.2

**Comment by AdminQQZ** [comment]
账号密码错误

**Comment by lieweisi** [comment]
https://login.yjhpos.com/#/login?account=lq1125&pwd=112233&isandroid=1&empcode=
可以打开啊，直接浏览器打开试试

**Comment by Justson** [comment]
暂时不支持data协议
