### ISSUE TITLE
在浏览器打开时保存图片没问题，app内保存图片时，会报这个错误，app读写权限都有

### ISSUE THREAD

**Issue by wlw67** [Justson/AgentWeb#975]
java.lang.RuntimeException: target file can't be created . 
        at com.download.library.DownloadSubmitterImpl$DownloadStartTask.run(DownloadSubmitterImpl.java:176)
        at com.download.library.DownloadSubmitterImpl$1.run(DownloadSubmitterImpl.java:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)

**Comment by btcw** [comment]
为啥关闭了，我也碰到了
