### ISSUE TITLE
文件上传闪退

### ISSUE THREAD

**Issue by code-rebooter** [Justson/AgentWeb#992]
Caused by: java.lang.IllegalStateException: showFileChooser result was already called
                                                                                                    	at ls0.onReceiveValue(chromium-TrichromeWebViewGoogle.apk-stable-443021033:8)
                                                                                                    	at com.just.agentweb.filechooser.FileChooser.cancel(FileChooser.java:480)
                                                                                                    	at com.just.agentweb.filechooser.FileChooser.onIntentResult(FileChooser.java:422)
                                                                                                    	at com.just.agentweb.filechooser.FileChooser$2.onChoiceResult(FileChooser.java:244)
                                                                                                    	at com.just.agentweb.AgentActionFragment.chooserActionCallback(AgentActionFragment.java:136)
                                                                                                    	at com.just.agentweb.AgentActionFragment.onActivityResult(AgentActionFragment.java:147)
                                                                                                    	at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:2905)
                                                                                                    	at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:2885)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
                                                                                                    	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:647)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)

**Comment by Justson** [comment]
```
 implementation 'com.github.Justson.AgentWeb:agentweb-core:v5.0.6-androidx' // (必选)
 implementation 'com.github.Justson.AgentWeb:agentweb-filechooser:v5.0.6-androidx' // (可选)
 implementation 'com.github.Justson:Downloader:v5.0.4-androidx'
```
