### ISSUE TITLE
Caused by: java.lang.IllegalStateException: showFileChooser result was already called

### ISSUE THREAD

**Issue by lishangwl** [Justson/AgentWeb#997]
at android.app.ActivityThread.deliverResults(ActivityThread.java:5163)
     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5204)
     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:236)
     at android.app.ActivityThread.main(ActivityThread.java:8060)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
 Caused by: java.lang.IllegalStateException: showFileChooser result was already called
     at ya.onReceiveValue(chromium-TrichromeWebViewGoogle.apk-stable-410410683:8)
     at com.just.agentweb.filechooser.FileChooser.cancel(FileChooser.java:480)
     at com.just.agentweb.filechooser.FileChooser.onIntentResult(FileChooser.java:422)
     at com.just.agentweb.filechooser.FileChooser$2.onChoiceResult(FileChooser.java:244)
     at com.just.agentweb.AgentActionFragment.chooserActionCallback(AgentActionFragment.java:136)
     at com.just.agentweb.AgentActionFragment.onActivityResult(AgentActionFragment.java:147)
find } for pid=16496 uid=10214 name=tethering scontext=u:r:vendor_systemhelper_app:s0:c512,c768 tcontext=u:object_r:tethering_service:s0 tclass=service_manager permissive=0
     at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:2905)
     at androidx.fragment.app.FragmentManager$9.onActivityResult(FragmentManager.java:2885)
     at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
     at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
     at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:638)
     at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
     at android.app.Activity.dispatchActivityResult(Activity.java:8517)

**Comment by lishangwl** [comment]
选择图片会崩溃
这个网站
https://www.dute.org/image-round

**Comment by Justson** [comment]
```
 implementation 'com.github.Justson.AgentWeb:agentweb-core:v5.0.6-androidx' // (必选)
 implementation 'com.github.Justson.AgentWeb:agentweb-filechooser:v5.0.6-androidx' // (可选)
 implementation 'com.github.Justson:Downloader:v5.0.4-androidx'
```
